### ISSUE TITLE
OSRS Bingo Setup

### ISSUE THREAD

**Issue by ArtillerySr** [kbuzsaki/bingosync#110]
Was hoping to submit a pull request for this but couldn't get the site to compile locally, so I guess I'll just open an issue. Sorry.

Please add the following Old School RS bingo list + description:
https://pastebin.com/f7rk5C2C

    GameType.osrs: {
        "name": "Old School Runescape",
        "variants": [
          (GameType.osrs, "F2P + Entrana", "OSRS")
        ],
    },

**Comment by kbuzsaki** [comment]
Live on the site now :)
