### ISSUE TITLE
New Skyrim Bingo

### ISSUE THREAD

**Issue by BattleSpartan36** [kbuzsaki/bingosync#125]
Hi I noticed there was no Skyrim Bingo generator so I decided to try to make one myself. This is my first time with making one of these so I expect something to be possibly wrong. Here is the link: https://pastebin.com/yhXntYHK 
Let me know if I need to make any changes!

**Comment by cmccandless** [comment]
I stumbled across bingosync looking to do Skyrim! I had my own list of goals cobbled together from a couple sources:

- Own a horse
- Gain 2 Dragon Souls
- Get a follower
- Join the Thieves Guild
- Join the Dark Brotherhood
- Giant Space Launch
- Pick up The Lusty Argonian Maid
- Escape from jail
- Get one or two handed to 40
- Join the Civil War
- Acquire one Daedric Artifact
- Eat a Human Heart
- Own a house
- Discover 20 location
- Become a werewolf or vampire
- Learn Bound Bow
- Acquire 7000 gold
- Win a fist fight
- Go to jail with a bounty of 1000+
- Learn 3 shouts
- Discover all hold capitals
- Kill 2 giants
- Find a standing stone (except first 3)
- Mine 10 ore veins
- Collect 3 unusual gems
- Kill a Dwarven Centurion
- Fus Ro Dah!

**Comment by BattleSpartan36** [comment]
If you'd like cmccandless, you can take ideas from mine and add some of yours or replace them. If you have any specific criticism with mine let me know and I'll change it. Either way I think a Skyrim bingo would be great and how it really hasn't been made yet baffles me.

**Comment by cmccandless** [comment]
Any idea how long someone very familiar with the game might take to get a bingo with your goals?

**Comment by BattleSpartan36** [comment]
I planned on it to be at least 3 hours. Like I said this is my first shot at making one and I'm basing it off of my own experience of the game, which is a good amount but I'm not a speedrunner and don't know many speedrunning techs.

**Comment by BattleSpartan36** [comment]
Also I appreciate having someone with knowledge of github having a look at this

**Comment by cmccandless** [comment]
> I'm basing it off of my own experience of the game, which is a good amount but I'm not a speedrunner and don't know many speedrunning techs.

Sounds familiar. I know that some of the tasks you've got at the bottom of the list would probably take me 3 hours by themselves, so a run with this board might be 4 or 5.

**Comment by kbuzsaki** [comment]
The skyrim generator is up now as "The Elder Scrolls V: Skyrim"

**Comment by cmccandless** [comment]
@BattleSpartan36 Having generated a few cards now with this generator, I'm thinking an "experienced, but no speedrunning knowledge" run might take 5-6 hours.
