### ISSUE TITLE
New bingocard - World of Warcraft

### ISSUE THREAD

**Issue by RaglanDiR** [kbuzsaki/bingosync#133]
Hi kbuzsaki,

Thanks for all your work on bingosync! I've got a new board I'd like to have added for World of Warcraft as below:

Name: New character race
Short name: Fresh Char

List of goals:
Complete Exiles Reach
Complete the Draenor introduction scenario
Complete the Legion introduction scenario
Complete the goblin starting area
Complete the worgen starting area
Complete a zone's quest line
Complete the Death Knight starting area
Complete the Demon Hunter starting area
Visit 5 innkeepers
Visit 10 innkeepers
Visit 15 innkeepers
Visit 20 innkeepers
Explore 1 zones fully
Explore 3 zones fully
Explore 5 zones fully
Reach level 15
Reach level 20
Die to fatigue
Die to lava/fire
Die to drowning
Die to falling
Die to a dungeon boss
Obtain resurrection sickness
Visit 4 capital cities
Visit 6 capital cities
Visit 8 capital cities
Visit 3 continents
Visit 5 continents
Visit 7 continents
Visit 5 flight paths
Visit 10 flight paths
Visit 20 flight paths
Jump off Thunder Bluff and survive
Jump off Dalaran
Jump off Teldrassil
Jump off Mount Hyjal
Jump off Outland
Jump off a tower
Jump off a cliff
Visit the top of Kun Lai summit
Visit the bottom of the ocean in Vashjir
Visit the Maelstrom
Visit Icecrown Citadel
Visit the Black Temple
Visit the Exodaar
Visit Silvermoon City
Visit the Gilneas
Visit the Blackrock Foundry
Visit Blackrock mountain
Visit Karazahn
Visit Strathholme
Visit Wyrmrest Temple
Visit the Great Wall of Pandaria
Visit the Goldshire Inn
Visit the big sword in silithus
Visit the Argent Tournament
Visit Gallywix's Pleasure Palace
Visit the Gates of Valour
Visit Booty Bay
Visit the Loch
Visit Ironforge Airport
Visit Fizzle & Pozzik's Speedbarge
Visit a class order hall
Visit an obelisk
Visit a lake
Visit a temple
Visit a worldtree
Visit a battleground portal
Visit a dome
Visit a pyramid
Visit an arena
Visit an isle
Visit a library
Visit a graveyard
Visit a necropolis/ziggurat
Visit the past (other than using the dark portal/chromie time)
Visit somewhere snowy
Visit somewhere sandy
Visit somewhere windy
Visit somewhere underwater
Visit somewhere underground
Visit 3 starting subzones
Visit 6 starting subzones
Click a Kalimdor dungeon waystone
Click a Kalimdor raid waystone
Click an Eastern Kingdoms dungeon waystone
Click an Eastern Kingdoms raid waystone
Click an Outland dungeon waystone
Click an Outland raid waystone
Click a Northrend dungeon waystone
Click a Northrend raid waystone
Click a Pandaria dungeon waystone
Click a Pandaria raid waystone
Click a Draenor dungeon waystone
Click a Draenor raid waystone
Click a Broken Isles dungeon waystone
Click a Broken Isles raid waystone
Click a Zandalar dungeon waystone
Click a Zandalar raid waystone
Click a Kul Tiras dungeon waystone
Click a Kul Tiras raid waystone
Enter a dungeon
Enter 3 dungeons
Enter 5 dungeons
Find 1 treasure
Find 5 treasures
Find 10 treasures
Obtain a key
Obtain a letter
Obtain a skull
Obtain oil
Obtain a badge
Obtain a silly hat
Obtain sludge/goo
Obtain something mechanical
Obtain something wooden
Obtain a tooth
Obtain a claw
Obtain a tusk
Obtain an offal
Obtain a bone
Obtain an eye
Obtain a web
Obtain an elemental item
Obtain an item that starts a quest
Obtain 10 crafting materials
Obtain 15 crafting materials
Obtain 20 crafting materials
Obtain something blue
Obtain something red
Obtain something yellow
Obtain something green
Obtain something orange
Obtain something brown
Obtain something purple
Obtain something white
Obtain something black
Obtain something grey
Eat 5 different foods
Eat 10 different foods
Eat 20 different foods
Eat Fish
Eat Poultry
Eat Dairy
Eat Bread
Drink 5 different drinks
Drink 10 different drinks
Drink 20 different drinks
Drink water
Eat/drink conjured food/drink
Loot 3 different cloths
Loot 5 different cloths
Loot 10 different cloths
Skin 3 different leathers
Skin 5 different leathers
Skin 10 different leathers
Mine 3 different ores
Mine 5 different ores
Mine 10 different ores
Gather 3 different herbs
Gather 5 different herbs
Gather 10 different herbs
Fish 3 up different fish
Fish 5 up different fish
Fish up 10 different fish
Make a bandage
Cook 3 different foods
Cook 5 different foods
Cook 10 different foods
Craft an item
Craft 3 items
Craft 5 items
Enchant a weapon
Disenchant an item
Disenchant 3 items
Disenchant 5 items
Survey a whole dig site
Complete an archeological artifact
Get a profession to level 10
Get a profession to level 25
Get a profession to level 50
Learn a recipe
Learn 3 recipes
Learn 5 recipes
Kill a skeleton
Kill a snake
Kill a dinosaur
Kill a ghost
Kill a gnoll
Kill a murloc
Kill a demon
Kill a crab
Kill a gorilla
Kill a troll
Kill a dwarf
Kill an elemental
Kill a naga
Kill a mammoth
Kill a gnome
Kill an elf
Kill a dragon
Kill a crocolisk
Kill a scorpid
Kill a wolf
Kill a bear
Kill a spider
Kill a vykrul
Kill a bat
Kill a bird
Kill a wind serpent
Kill an undead
Kill a clefthoof
Kill a yeti
Kill a robot
Kill an orc
Kill a kobald
Kill an insect
Kill a human
Kill a quillboar
Kill a beast on each continent (except Shadowlands)
Kill an elite (dragon frame)
Kill a rare (silver frame)
Kill a dungeon boss
Kill a named npc
Kill 25 creatures
Kill 50 creatures
Kill 100 creatures
Kill 25 critters
Kill 50 critters
Kill 100 critters
Shoot a gun/cannon
Tame an animal
Summon a totem
Say a prayer
Obtain an artifact weapon
Use a talented spell
Summon a demon
Dismiss a pet
Change form
Enter stealth
Wield 2 weapons
Use a shield
Revive yourself after dying
Cast a healing spell
Cast a lightning spell
Cast a nature spell
Cast a holy spell
Cast a shadow spell
Cast a frost spell
Cast a fire spell
Cast an arcane spell
Generate 100 rage
Run out of mana
Heal an NPC
Use a trap
Get a haircut
Sit on a throne
Use a mission table
Ring a gong
Drink a potion
Read a book
Change your transmog
Use a controllable vehicle
Talk to an animal
Set something on fire
Put out a fire
/pet a dog
/pet a cat
/pet a rabbit
/pet a named animal
/love 5 critter for the achieve 'To all the squirels I've loved before'
/love 10 critter for the achieve 'To all the squirels I've loved before'
/love 5 critters for the achieve 'To all the squirrels who've shared my life'
/love 5 critters for the achieve 'To all the squirrels who cared for me'
/love 5 critters for the achieve 'To all the squirrels I once caressed'
/love 5 critters for the achieve 'To all the squirrels through time and space'
/love 5 critters for the achieve 'To all the squirrels I love despite their scars'
/love 5 critters for the achieve 'To all the squirrels I set sail to see'
Slay 5 critters for the achieve 'Pest control'
Slay 10 critters for the achieve 'Pest control'
Walk through the dark portal
Ride a zeppelin
Ride a train
Ride a boat
Ride an elevator
Take a flight path
Use 15 unique portals
Use 20 unique portals
Use your hearthstone
Use your hearthstone 2 times
Use your hearthstone 3 times
Complete 10 quests
Complete 20 quests
Complete 30 quests
Have a reputation at honoured
Complete a daily (blue) quest
Complete a world quest
Obtain 2 tabards
Obtain 3 tabards
Obtain 50 silver
Obtain 1 gold
Obtain 5 gold
Buy a green item
Sell a green item
Sell an item to a vendor in a dungeon
Loot a grey item and equip it
Loot a green item and equip it
Loot a blue item and equip it
Equip a trinket
Equip 2 rings
Get cursed
Get poisoned
Get burnt
Get stabbed (and bleed)
Have 3 buffs at once
Have 5 buffs at once
Have 7 buffs at once
/wave at Khadgar
/wave at Garrosh Hellscream
/wave at a dragon aspect
/wave at an enemy faction leader
/wave at an Undercity banker
/wave at a Teldrassil banker
/wave at Tirion Fordring
/wave at Mankrik's wife
/wave at Sylvanus
/wave at Thrall
/wave at Anduin Wrynn
/wave at Magni Bronzebeard
/wave at the Lich King
/wave at Bwomsamdi
/wave at Jaina Proudmoore
/wave at Harrison Jones
/wave at Hemit Nesingwary
/wave at Brann Bronzebeard
/wave at Illidan Stormrage
/wave at Malfurion Stormrage
/wave at Deathwing
/wave at a Warlord of Draenor
/wave at Guldan
/wave at Maiev Shadowsong

**Comment by kbuzsaki** [comment]
This is up now :)

I named the variant "New Character" with short name "WoW New Char", let me know if that's inaccurate.
