### ISSUE TITLE
New Bingocard - Metroid Prime Randomizer

### ISSUE THREAD

**Issue by AeroRaiser** [kbuzsaki/bingosync#135]
Heya! Got a board for Metroid Prime I want to have added. Thanks for all the work on Bingosync!

Game Name: Metroid Prime Randomizer
Short Name: MPR

2 Types of boards for this

Board Type: Random Goals
Variant Name: Chaos
Goal List: https://pastebin.com/CgLxMJ7Z

Board Type: SRL
Variant Name: Balanced
Goal Layout: https://pastebin.com/myZR0w8U

**Comment by AeroRaiser** [comment]
*Added 6 more goals at end, and fixed spelling on 1 goal.

**Comment by AeroRaiser** [comment]
1 final edit, with help from the MPR Community set up around 50 more goals to allow for an SRL / Balanced variant to be possible. Included the necessary formatting for such as well as the text file for the goal list to give access to 2 variants.

**Comment by kbuzsaki** [comment]
Both variants are up now :)
