### ISSUE TITLE
Update Terraria Board 

### ISSUE THREAD

**Issue by psionyxSR** [kbuzsaki/bingosync#146]
For the "Pre-Hardmode" Variant:
[https://pastebin.com/YEhVbe1e](https://pastebin.com/YEhVbe1e)
Balanced some of the goals around.

**Comment by kbuzsaki** [comment]
This is up now :)

**Comment by psionyxSR** [comment]
Thanks for getting to this.

It looks like you may have overwritten the 1.3 PreHM variant instead of the non-1.3 one.

**Comment by kbuzsaki** [comment]
Oh, whoops, you're right. I'll be able to resolve this in about an hour.

**Comment by kbuzsaki** [comment]
This should be resolved now, please let me know if it's not.
