### ISSUE TITLE
Updated Goals: Metroid Prime Randomizer

### ISSUE THREAD

**Issue by AeroRaiser** [kbuzsaki/bingosync#148]
Updated Goal List

Randomizer Chaos Variant Goal list: https://pastebin.com/fZB71xVj
Randomizer Balanced Variant Goal list: https://pastebin.com/wrWQjHXd

Cleaned up some naming and added goals. Instead of listing a bunch of changes. Just pasted the new lists in here.

**Comment by kbuzsaki** [comment]
This is up now :)
