### ISSUE TITLE
Add Metroid Prime 2: Echoes Bingo

### ISSUE THREAD

**Issue by BashPrime** [kbuzsaki/bingosync#151]
Thank you!

Game Name: Metroid Prime 2: Echoes
Short Name: mp2

Two board variants:

Board Type: SRL
Variant Name: Randomizer Balanced
Goal Layout: https://github.com/BashPrime/metroid-prime-bingo/releases/download/v0.1.0/echoes_bingo.js

Board Type: Random Goals
Variant Name: Randomizer Chaos
Goal List: https://github.com/BashPrime/metroid-prime-bingo/releases/download/v0.1.0/echoes_bingo.txt

**Comment by kbuzsaki** [comment]
This is up now :)
