### ISSUE TITLE
New Game Request: New Super Mario Bros. U

### ISSUE THREAD

**Issue by TrevorBushnell** [kbuzsaki/bingosync#152]
Thanks for considering this. 

Game Title: New Super Mario Bros. U
Short Name: NSMBU

See the .txt file attached for a list of general goals to use
[NSMBUDXGoals.txt](https://github.com/kbuzsaki/bingosync/files/6563783/NSMBUDXGoals.txt)

**Comment by kbuzsaki** [comment]
This is up now :)
