### ISSUE TITLE
Please update Yooka Laylee's board

### ISSUE THREAD

**Issue by tipdaddy78** [kbuzsaki/bingosync#153]
We have re-worked the Yooka-Laylee board.  Please update it with the attached file.
[yooka-laylee-goals.txt](https://github.com/kbuzsaki/bingosync/files/6565748/yooka-laylee-goals.txt)

**Comment by kbuzsaki** [comment]
This is up now :)

**Comment by tipdaddy78** [comment]
Thank you!
