### ISSUE TITLE
Add New Super Mario Bros 2 Support

### ISSUE THREAD

**Issue by TrevorBushnell** [kbuzsaki/bingosync#162]
Thanks for considering this.

Game Title: New Super Mario Bros. 2
Short Name: NSMB2

See the .txt file attached for a list of general goals to use

[nsmb2_goals.txt](https://github.com/kbuzsaki/bingosync/files/6796344/nsmb2_goals.txt)

**Comment by kbuzsaki** [comment]
It's up now :)
