### ISSUE TITLE
Horizon Zero Dawn Bingo

### ISSUE THREAD

**Issue by AltinCloak** [kbuzsaki/bingosync#174]
Hi, I sent you a message on twitter but you have not responded, Here is what I said. 

Hi Saltor, I just thought I would give you a heads up that I will be submitting a bingo board either later today or early tomorrow.

here is the stuff. https://pastebin.com/YyFvzgFw is the SRL-syle goal list. the game is Horizon Zero Dawn. And the abbreviation is HZD: TFW.

btw, this is one of three bingo boards for HZD, the other two are still being worked on.

**Comment by AltinCloak** [comment]
hey, sorry to do a big flip flop on you but I redid the SRL. Will this work? https://pastebin.com/YyFvzgFw (it's not working in custom boards)

**Comment by AltinCloak** [comment]
hey, it's been a few weeks. When can I expect to board to be up and running?

**Comment by AltinCloak** [comment]
^^ >:(

**Comment by kbuzsaki** [comment]
This game was added in #203, feel free to contact the author and send a pull request if you'd like to update it.

In the future, please be kind when interacting on the issue tracker, maintaining bingosync is something I do in my free time at no cost to you, and life often gets in the way. Angry messages don't help anyone :)

**Comment by AltinCloak** [comment]
hey, I'm sorry about how I acted. Though one thing I have to ask, the items in the board don't look anything like any of the files I sent you. If you could let me know why that would be great.

**Comment by kbuzsaki** [comment]
Another person also requested this game in #203, which I merged and deployed without realizing the conflict.

Feel free to reach out to that person if you'd like to collaborate on improving the existing goal list, or if you think your two lists serve different purposes I can add them as multiple variants for the same game -- just let me know what the variant names should be.

**Comment by AltinCloak** [comment]
well, here is a sub category you could call TFW or The Frozen Wilds
https://pastebin.com/YyFvzgFw

**Comment by AltinCloak** [comment]
and I have some other boards that I would just need to put in SRL format
