### ISSUE TITLE
Counter Strike Bingo Board

### ISSUE THREAD

**Issue by OfficerFrog** [kbuzsaki/bingosync#176]
Here is the SLR JSON for a Counter Strike Bingo Board. https://pastebin.com/kXG7Dkdu

Full game name is Counter Strike Global Offensive. Abbreviation is CS GO

Let me know if there are any corrections that need to be made. 

Thank you for managing a great bingo board site.

**Comment by OfficerFrog** [comment]
Previous paste bin expired. here's a new paste bin with some added squares.

https://pastebin.com/bHax0Nx2

**Comment by OfficerFrog** [comment]
Any update on when we can expect these boards to be added?

**Comment by kbuzsaki** [comment]
The above pastebin has expired again, please reopen with a new one. 

I'm pretty irregular with when I do updates, sometimes it can be months between if life is busy, but ideally I'd be putting things up 1-2 times a month to keep the queue short.
