### ISSUE TITLE
Oceanhorn 2 Bingo

### ISSUE THREAD

**Issue by Eraxis** [kbuzsaki/bingosync#177]
Hey !
I sent you a pm on Twitter to add a generator for the Bingosync but it seems u didn't see it (maybe there was a problem with Twitter pm).

1. The generator or goal list to use -> https://pastebin.com/HUQt1rvu
2. The name you'd like -> Oceanhorn 2: Knights of the Lost Realm
3. The abbreviated name you'd like -> Oceanhorn 2

This is the first time I've tried to make a generator for a bingo so don't hesitate to tell me if something is wrong :)

**Comment by kbuzsaki** [comment]
This is deployed now :)
