### ISSUE TITLE
Rayman (PS1) updated goals

### ISSUE THREAD

**Issue by Thexterax** [kbuzsaki/bingosync#179]
Hi there, 

Please update the rayman (PS1) goals with these:

https://pastebin.com/uVpesUbS

The current ones can be overwritten with this list!

keep me posted

- Thextera

**Comment by Thexterax** [comment]
To save you guys some trouble, I updated the pastebin to reflect the current code.

**Comment by kbuzsaki** [comment]
This is up now :)
