### ISSUE TITLE
Link's Awakening Dungeon Dive Bingo

### ISSUE THREAD

**Issue by MaxBov** [kbuzsaki/bingosync#181]
Hi there!

This is a Bingo list for the Link's Awakening Randomzier mode 'Dungeon Dive'. Dungeon Dive is a specific randomization mode that changes the over-world of Link's Awakening and creates an entirely new and unique randomized experience. This is NOT and update to the existing Bingo, but rather an entirely new variation of Bingo. This is an addition to the "Variant" drop-down menu that occurs. (Eg. in some games like Ocarina of Time there are multiple variations of bingo modes) This new Link's Awakening 'Dungeon Dive' Bingo is a brand new way to play LADX Randomizer. 

Generated list - https://pastebin.com/UA5scxHP
Drop down name - Dungeon Dive
Possible room list - LADXR (Dive)

Thank you for considering this.

**Comment by MaxBov** [comment]
Hey there! Any update on when the website will be updated?? Hopefully soon??

**Comment by kbuzsaki** [comment]
This is live now :)

(thanks for your patience with the long delay, haha, my free time for bingosync certainly comes and goes)
