### ISSUE TITLE
Update the Hollow Knight goal list

### ISSUE THREAD

**Issue by simutk** [kbuzsaki/bingosync#184]
I would like to see it added to the Hollow Knight generator.

Variant Name: Item Randomizer - JP
Short Name: Item Rando JP
https://drive.google.com/file/d/1js474JLFCdZZHhM3Q9iHrXF-Xgby5FWr/view?usp=sharing

It was created by rewriting the following one. Please let me know if there are any problems.
https://github.com/kbuzsaki/bingosync/blob/master/bingosync-app/generators/hollow_knight_item_rando_generator.js

**Comment by JasonILTG** [comment]
Incorporated into this PR: https://github.com/kbuzsaki/bingosync/pull/197

**Comment by kbuzsaki** [comment]
Already merged in #197
