### ISSUE TITLE
REQUEST ADD: Drakengard 2

### ISSUE THREAD

**Issue by M45HMX** [kbuzsaki/bingosync#185]
Requesting for Drakengard 2 to be added to bingosync.

I have attached a link to a Spread Sheet that will be updated further over time that currently contains goals sorted by difficulty.
Also included is a Difficulty Tiering List with numbers of the associated goals of each difficulty for use in randomization of the boards if these could be added as preset randomization options. I have marked 3 based on Rating to indicate the length associated to the randomization styles which is based around Lockout or Team Blackout playstyles which is the most ideal format to play.

Due to the games linearity the goals as designed to be completed either along the way at a minimum point or above or from optional repeatable sections once they come available from general progression.  Multiple Goals can be completed together which create their own synergies example Free Expedition and Obtain Weapon is one combination that exists along with Time Attack style goals that can be completed at various points along side those. 

The document currently contains basic info on the goal and will be updated to include a help/cheat sheet for new players or referencing for achieving goals.

The Link to the Spread Sheet: [Drakengard 2 Bingo](https://docs.google.com/spreadsheets/d/16XCjcIwaC5J9cpDsBWMkyA7MjjG6z95qq0J8qDeUpwI/edit?usp=sharing)

NAME: Drakengard 2
ABBREVIATION: DOD2
GENERATOR: Requesting Custom based on the information provided within the doc and explanation.

Feel free to reach out to me for more information regarding this request.
~ MASH [TWITTER](https://twitter.com/MASH_MX) , [NieR & Drakengard Speedruns Discord](https://sponsoredbydrakengard.com/) , [Speedrun.com Profile](https://www.speedrun.com/user/MASH)

**Comment by kbuzsaki** [comment]
Hi there, please put these goals in one of the formats listed on bingosync.com/about, I can't feed a spreadsheet into any of my tools for creating bingo generators :)

Closing since there's no action for me to take, please re-open when you're ready for me to add it.

**Comment by M45HMX** [comment]
I kept getting bad Gateway errors for the site and pages linked.
Can you give me an example of how you would like to have it formatted to be use able.
I tried to keep them grouped to be added as per the Tier's so they could be randomized with those #'s in mind since length could vary a good amount other wise with the testing that has been done for what is currently in the doc.

**Comment by kbuzsaki** [comment]
Thanks for reporting the bad gateway errors, those should be fixed now.

You can find the example goal lists on bingosync.com/about under the "Adding or Updating Generators" section.
