### ISSUE TITLE
Request New Generator: SMRPG Randomizer

### ISSUE THREAD

**Issue by Cynas19** [kbuzsaki/bingosync#188]
Requesting the addition of a new generator for bingosync:

Name: Super Mario RPG Randomizer
Abbreviation: SMRPG Rando
List (in JSON format): [https://pastebin.com/QTJEBFs0](https://pastebin.com/QTJEBFs0)

List (sheets format, column A): [https://docs.google.com/spreadsheets/d/1boFoxkZ-0Lh960vhs3r5IeEqd9GInoCqPN9fE1MgXK8/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1boFoxkZ-0Lh960vhs3r5IeEqd9GInoCqPN9fE1MgXK8/edit?usp=sharing)

Thank you for your hard work on the website, and helping create and expand the community of gamers!

-Cynas

**Comment by kbuzsaki** [comment]
This is deployed now :)
