### ISSUE TITLE
Suggestion for bingo game - Days Gone

### ISSUE THREAD

**Issue by PoulSkaldyr** [kbuzsaki/bingosync#191]
Hi, im very new to this put i find the bingo very intriguing and really wanted to do some with my friends. 
There are many games to enjoy on BingoSync but some good ones are really missing, like Horizon Zero Dawn (which i can see your already working on) and Days Gone. 
So i hope you read this message, not as preasure but as a suggestion for improvement. :)

Regards.

**Comment by kbuzsaki** [comment]
I don't create goal lists, I only add them when other people create them and submit them. Feel free to put one together for this game and submit it :)

**Comment by PoulSkaldyr** [comment]
Oh okay, again, i dont have any experience with making these sorts of things, so do you know where i can find any guides or something like that?
Just to make sure its done properly :)

**Comment by PoulSkaldyr** [comment]
As far as i can tell from looking at some other examples you just need:

1. A list of the "goals" so to speak, and they need to be arranged into 25 sections with a couple of "goals" in each. (arranged so that each section is named "bingoList[1-25] = [" and then the goals them selves with "name:".
2. The name of the game itself

Is that correct or am i missing something??

**Comment by MaxBov** [comment]
I think that's right I did mine a little differently, but depends on the game. In fairness I don't think the BingoSync website has been updated for a LONG while, (ive been waiting for about a month now) Hopefully all of it gets updated soon! Ive been looking forward to playing it.

**Comment by PoulSkaldyr** [comment]
Oh okay, well ill try making and submit it, hopefully they will update it soon :)
Thanks for the help!

**Comment by kbuzsaki** [comment]
Definitely feel free to open an issue or pull request with a goal list when you're ready to submit it, but I'm going to close this issue for now since there's no action for me to take :)
