### ISSUE TITLE
Request New Bingo Board: Call of Duty: Black Ops Zombies Saga

### ISSUE THREAD

**Issue by RandomUser14PS4** [kbuzsaki/bingosync#192]
Game Name: Call of Duty: Black Ops Zombies Saga
Short Name: CoD Zombies
List: https://pastebin.com/LV8Zp02k

All of the 75 Challenges were designed to be able to be completed in all 5 Call of Duty: Black Ops games in the Zombies mode provided that all maps are available. There are no difficulty ratings because certain games make challenges more or less difficult.

**Comment by kbuzsaki** [comment]
This is deployed now :)
