### ISSUE TITLE
New Game Request - Five Nights at Freddy's: Security Breach

### ISSUE THREAD

**Issue by BraydenErger** [kbuzsaki/bingosync#194]
Five Nights at Freddy's Security Breach has become the top 3 active game on Speedrun.com after being out for just 2 weeks. I'd like to help grow the community with its own bingo board.

1 - I have 4 differnet goal list variants for the game, all are simple goal lists.
a. (Everything) - https://pastebin.com/NeVykWaS
b. (No Collectibles) - https://pastebin.com/iwtU1e9d
c. (Only Collectibles) - https://pastebin.com/ABuFzGxN
d. (Speedrun Categories) - https://pastebin.com/GeUUbyC5

2 - Game Name - "Five Nights at Freddy's: Security Breach"

3 - Abbreviated Name - "FNaF: SB"

Thanks a bunch!

**Comment by kbuzsaki** [comment]
These are live now :)
