### ISSUE TITLE
Requesting changes for Terraria

### ISSUE THREAD

**Issue by Maxoverpower** [kbuzsaki/bingosync#196]
Terraria already exists on bingosync, I want changes to 1 of the existing boards and 2 more added.
1. "Pre-Hardmode" - rename to "Pre-Hardmode Classic" and there's goal changes here https://pastebin.com/gkhLE5Ru
2. "Pre-Hardmode Journey" - new board with these goals https://pastebin.com/bBtSyxLE
3. "Hardmode Journey" - new board with these goals https://pastebin.com/0GJjAHGn
And in that order, please.

**Comment by kbuzsaki** [comment]
Hi -- I'm happy to add the new variants for you but I noticed that the existing Pre-Hardmode variant was added by a different user, @psionyxSR. Have you gotten permission from them / their community to update the existing variant?

I'll add the new variants later today and then close this issue. Feel free to open a new issue for the update to the existing version once that's cleared up.

**Comment by kbuzsaki** [comment]
The two "Journey" variants are live now :)

**Comment by psionyxSR** [comment]
Yes please update the prehardmode bingo

**Comment by kbuzsaki** [comment]
Pre-Hardmode is now also updated :)
