### ISSUE TITLE
A New game request for Pokémon Legends: Arceus

### ISSUE THREAD

**Issue by Nukelasi** [kbuzsaki/bingosync#199]
For those who want to have fun with buddies or yourself, I've made a JSON code with 289 possible goals so far. Be it capture a specific pokemon or craft a specific item to fill a bingo card. Intended for randomizing only.
[legendsbingo.txt](https://github.com/kbuzsaki/bingosync/files/8023820/legendsbingo.txt)

**Comment by kbuzsaki** [comment]
Someone else added this game in #198, please contact them if you want to update it :)
