### ISSUE TITLE
lack of response concerning Bingosync moderation

### ISSUE THREAD

**Issue by AltinCloak** [kbuzsaki/bingosync#201]
Hey @kbuzsaki . Their have been lots of things asked of you without response. While I understand that you have a real life just like all of us I find it very irresponsible the lack of care or comment on Bingosync moderation. I would really appreciate (and I don't think I'm the only one) if you could give some sort of comment on when your next "push of generator updates in periodic batches" will be.

**Comment by kbuzsaki** [comment]
I'm happy that people continue to enjoy Bingosync, but I do not owe you or anyone else my time, attention, or labor for new additions. Badgering me does not change that, and, frankly, it makes me want to help you less. Please keep that in mind when you’re basically asking someone to do you a favor.

If you want to play a new game on Bingosync before I upload it, you are welcome to use one of the many options for loading a custom board or custom goal list, as listed under the variants for the `Custom (Advanced)` game type.
