### ISSUE TITLE
Board desyncs on new board creation

### ISSUE THREAD

**Issue by Gikkman** [kbuzsaki/bingosync#206]
I encountered this when I was toying around and trying out this page.

I created a new room (`6LLiTNHTQHy6s9pQ88w_Sw`) using the Advanced - Custom Random settings, and entered as player `test`. Then, I opened a new Private Browsing window (Firefox), and joined the same room as a spectator. Initially it worked well, and the spectator could see what the player did. But when I generated a new board (in the same room), the spectator was not updated with the new board but rather still saw the old board. The marked tiles weren't cleared for the spectator either, but they were for the player.

Subsequent board changes are still updated though, so when the player ticked a tile, the spectator saw those tile updates, it was just that the names on the tiles weren't correct, and the spectator still had tiles marked from the previous card still around.

So I think there might be a case where new boards aren't pushed to the clients, which causes this desync.

I could probably try to investigate this a bit if you'd like to (once I figure out how to run this application locally).

**Comment by kbuzsaki** [comment]
My guess is that this was probably a symptom of #243 (rate limiting of requests for the board endpoint to prevent people from scraping it). That rate limiting is done per IP-address, so when you open up multiple browsers for the same room they are competing with each other.

I think the solution is to add a retry on the client side and perhaps to relax the rate limit now that I've added an index on the uuid column.

Thanks for the report helping to confirm the rate limit behavior affecting users in the wild :)
I'm going to close this issue as a duplicate and track the fix in #243.
