### ISSUE TITLE
Sending messages via the api

### ISSUE THREAD

**Issue by PrinceKomali** [kbuzsaki/bingosync#207]
Hi! I've been interacting with the bingosync api now but I can't figure out how to use the endpoint `/api/chat`, as I need to have a bot send messages in the chat to trigger other things. Is there a way to do this?

**Comment by kbuzsaki** [comment]
What problems are you having?

You should be able to see what a valid request looks like using your browser's developer tools. Make sure that your bot has authenticated and is sending requests with a cookie.
