### ISSUE TITLE
No board for Banjo Kazooie - unable to import JSON file

### ISSUE THREAD

**Issue by Tilyn-the-Dropbear** [kbuzsaki/bingosync#212]
Context:
So I plan on doing a bingo of Banjo Kazooie (N64) and realized there wasn't already a bingo board for it - no problem I thought, let's just do it in the custom (advanced) option, I created a JSON file which worked for it, until my computer broke and I needed a new one. Once that happened I recovered my document and thought it needed a few more because what I had was just for testing at that point, and there should be enough points so I could split it if I ever did a 1 world + lockout run, so continued in the same style - 

ISSUE:
I went to re-test just to make sure after getting 25 for Mumbos Mountain and it states it is an invalid JSON (I followed the link to JSONLint to see where the issue was) and it states the issue is a parse error on line 1:
[{                  "...
---^
Expecting 'String', '}', got 'undefined'

This part worked originally and I'm unsure on how to fix it as I don't usually work with JSONs can someone help?

For reference here is what I tested:

[ {“name”: “100% MM”},
{“name”: “Blue Jinjo in MM”},
{“name”: “Pink Jinjo in MM”},
{“name”: “Orange Jinjo in MM”},
{“name”: “Green Jinjo in MM”},
{“name”: “Yellow Jinjo in MM”},
{“name”: “All Jinjos in MM”},
{“name”: “All Jiggys in MM”},
{“name”: “All Notes in MM”},
{“name”: “All Extra Honeycombs in MM”},
{“name”: “Learn Talon Trot (MM)”},
{“name”: “Learn Beak Buster (MM)”},
{“name”: “Learn Eggs (MM)”},
{“name”: “Become a Termite (MM)”},
{“name”: “1st Grunty’s Lair Jiggy”},
{“name”: “Termite tower Jiggy (MM)”},
{“name”: “Congas’ Secret Treasure (MM)”},
{“name”: “Orange for Chimpy (MM)”},
{“name”: “Jiggy in the eye (MM)”},
{“name”: “Shooting Conga Jiggy (MM)”},
{“name”: “Juju Jiggy (MM)”},
{“name”: “Slippery slope Jiggy (MM)”},
{“name”: “Talon Trot Jiggy (MM)”},
{“name”: “Hut destroyer Jiggy (MM)”},
{“name”: “1 Extra Honeycomb (MM)”}]

Cheers

**Comment by Tilyn-the-Dropbear** [comment]
also just realised i left the space between '[' and '{' in, in the first line, which i put in to test if that was the issue

**Comment by kbuzsaki** [comment]
It looks like your json is using "curly double quote" characters (`“`) instead of regular straight double quote characters (`"`). json requires that the double quotes are regular straight double quotes, not curly.
