### ISSUE TITLE
several updates on my old generators and new generators added

### ISSUE THREAD

**Issue by adamkaak** [kbuzsaki/bingosync#221]
Hello I've updated some of my old generators(102 dalmatians, a bug's life, donald duck goin' quackers) and added new ones(Spyro 1, Crash 2, Crash 3) and made a new version for Toy Story 2.
I also made sure to edit game_type.py for the new additions.
I already made a pull request can you please accept it thank you.
https://github.com/kbuzsaki/bingosync/pull/214
https://github.com/kbuzsaki/bingosync/pull/215
https://github.com/kbuzsaki/bingosync/pull/216
https://github.com/kbuzsaki/bingosync/pull/217
https://github.com/kbuzsaki/bingosync/pull/218
https://github.com/kbuzsaki/bingosync/pull/219
https://github.com/kbuzsaki/bingosync/pull/220
https://github.com/kbuzsaki/bingosync/pull/222

**Comment by kbuzsaki** [comment]
I believe these are all merged now, thanks for sending them as pull requests :)

In the future, it's helpful to keep them a bit more self contained (especially, keep the game_type updates packaged with the related generator), but it's not too much of a big deal. It's also fine to submit a single pull request updating several games at once if you'd like.
