### ISSUE TITLE
New Game Request: Crystal Clear by SS

### ISSUE THREAD

**Issue by HopeWasHere** [kbuzsaki/bingosync#227]
Hello,
I would love to request Crystal Clear on Bingosync. I have created a goal list, but I am very new to the process, so I hope it works correctly. Thanks again, I have loved using Bingosync and look forward to many more fun games through the service!
https://pastebin.com/MdafzmDq

**Comment by kbuzsaki** [comment]
Hi, thanks for your game request :)

Based on the difficulty tier numbers in your list, it looks like you're trying to create an SRL v5 goal list. However, it looks like your goal list currently has 67 tiers but an SRL v5 generator needs exactly 25 tiers to work, it won't work with fewer.

I've instead put up your game as a "simple goal list" which ignores the types and the tiers but will give you something to experiment with :)

**Comment by HopeWasHere** [comment]
Oh, that makes sense. I wasn't sure how it worked, but I think I'm getting it now. Thanks for putting it up, it's been a lot of fun to mess with! Here is the (hopefully) corrected goal list, if getting it updated is an option: https://pastebin.com/P9UrjiX5
Thanks again for such a great project, it's always fun to see what new games are getting added :)
