### ISSUE TITLE
"Custom (Advanced)" bingo with SRL v5 rule-set doesn't work (JSON parsing issue)

### ISSUE THREAD

**Issue by brunodema** [kbuzsaki/bingosync#228]
Hi

I was trying to set up a test room on bingosync with a SRL v5 rule-set, and I noticed that the form fails to parse the file format mentioned on the 'about' page. I even tried to use the example itself (https://pastebin.com/Ue2wcMcY), but it fails to parse the contents.

It seems pretty obvious that the reason for failing is that the example documentation shows goals structured in JavaScript (or whatever language it is), which is completely different from JSON. I was just wondering if the form would recognize any other sort of JSON formatting, i.e., a JSON schema created specifically for SRL v5.

**Comment by kbuzsaki** [comment]
I updated the example in b75825f77504e3f4021bd3ba8b7497f1b271a2d9 to be one that should parse correctly.

You're right that the old example was javascript, which is historically how bingo lists had been written on SRL. The "Custom SRLv5" option in bingosync though requires the input to be json that matches what the javascript code would have produced. Sorry about the confusion, hope the new example helps :)

**Comment by brunodema** [comment]
Thanks @kbuzsaki :)
