### ISSUE TITLE
Request: Game Update - LEGO Batman V1.10.1 & V1.10.2

### ISSUE THREAD

**Issue by Prnced** [kbuzsaki/bingosync#230]
Hello!

The LEGO Batman speedrunning community would like to make some updates to the bingo generators for LEGO Batman.
1. We do not need all six variants that are currently present. "Normal", "Long", "Semi-Random Level Names", and "Semi-Random Level Numbers" can all be removed. "Random Level Names" and "Random Level Numbers" can be renamed "Level Names" and Level Numbers", respectively.
2. There have been some updates to the goals for "Level Names" and "Level Numbers". Here are the links to the pastebins for each variant:
     a. "Level Names": https://pastebin.com/Ubj2kZCU
     b. "Level Numbers": https://pastebin.com/qgA7VqHV

That is all. Thank you!
- Prnced

**Comment by kbuzsaki** [comment]
These updates are live now :)
