### ISSUE TITLE
Request: Randomizer Option for Super Metroid

### ISSUE THREAD

**Issue by Murphmario** [kbuzsaki/bingosync#231]
The current normal option for Super Metroid isn't all that suited for Super Metroid with options like skipping items and having to collect x amount of items in an area, especially in cross-game randomizers like Archipelago where skipping items are 100% down to luck. Having a randomizer option that removes these goals would be nice.

**Comment by lenophis** [comment]
The original SM bingo was made for solo play and races. Multiworld wasn't a concept in 2013. Any solo randomizer generator should work just fine with SM bingo, unless you're using non-standard settings.

As for multiworld, yeah, a new set of goals would need to be made.

**Comment by Murphmario** [comment]
> The original SM bingo was made for solo play and races. Multiworld wasn't a concept in 2013. Any solo randomizer generator should work just fine with SM bingo, unless you're using non-standard settings.
> 
> As for multiworld, yeah, a new set of goals would need to be made.

Except that doesn't solve the issue of having to collect a specific amount of items in an area, since there's no guarantee that enough of a specific item would be placed in a certain area due to how randomizers work.

**Comment by kbuzsaki** [comment]
Feel free to propose a goal list when you have one, but that discussion would be better to have with other folks in the super metroid community :)

I'd like to keep bingosync issues as issues that are actionable by me, either because they're a feature/bug or because there's a specific goal list being proposed that I can use.
