### ISSUE TITLE
New Bingo Category: Metroid Dread Randomizer

### ISSUE THREAD

**Issue by AeroRaiser** [kbuzsaki/bingosync#232]
Have a new board for Metroid Dread!

Name: Metroid Dread Randomizer
Short Name: MDR

2 Board Types

Board Type: SRL
Variant Name: Balanced
Goal Layout: https://pastebin.com/c9FsM7Kn

Board Type: Random Goals
Variant Name: Chaos
Goal List: https://pastebin.com/ssRTxWix

**Comment by kbuzsaki** [comment]
These are live now :)
