### ISSUE TITLE
Paper Mario Bingo Variant

### ISSUE THREAD

**Issue by StarryArie** [kbuzsaki/bingosync#239]
Hi, I'm from the Paper Mario community, and I'd like to get a new variant put on Bingosync.

1. Here is the SRL-style list with the information for the generator: [pmario_bingo3_electric_beegalee.txt](https://github.com/kbuzsaki/bingosync/files/9659755/pmario_bingo3_electric_beegalee.txt)
2. The game is Paper Mario and the name for the new variant should be "2022".

Thank you!

**Comment by kbuzsaki** [comment]
This is live now :)
