### ISSUE TITLE
Add Skyward Sword Bingo

### ISSUE THREAD

**Issue by lepelog** [kbuzsaki/bingosync#24]
It would be really nice to have a Skyward Sword bingo card, goals are defined [here](https://github.com/indykenobi/SSBingo/blob/master/ssbingo.js)

**Comment by kbuzsaki** [comment]
Added in a5f1619e6ae2f31f3a9ad1ccbc087330cb630fb0 and live on the site now :)

**Comment by Floha258** [comment]
The goal list has been updated, would be nice to get an update here too

**Comment by kbuzsaki** [comment]
Updated :)
