### ISSUE TITLE
Game add: Threads of Fate

### ISSUE THREAD

**Issue by shinytentacruel** [kbuzsaki/bingosync#246]
Could I please get a new game added for Bingo boards?

- Game name: Threads of Fate
- Abbreviated name: Threads of Fate
- Goal list:  https://pastebin.com/BumpGpte

Thanks!

My contact info:
Discord: ShinyTentacruel#6464
email: spencerhhh@aol.com
twitter:  @adecentfellow11

**Comment by kbuzsaki** [comment]
This is up now :)
