### ISSUE TITLE
Horizon Zero Dawn board update

### ISSUE THREAD

**Issue by AltinCloak** [kbuzsaki/bingosync#248]
firstly, I've been unable to get a hold of tht1kd (the person who made the board that got implemented) and so I was wondering if you could just change his board's name to something like tht1kd-fullgame or tht1kd-normal?

secondly could you add this board (https://github.com/AltinCloak/HorizonBingo/blob/main/HZD/bingo_TFW.JSON) as a second variant and call it 'The Frozen Wilds'?

**Comment by kbuzsaki** [comment]
This variant is up now as "The Frozen Wilds"
