### ISSUE TITLE
NEW Hitman 3 (9 variants) Generator

### ISSUE THREAD

**Issue by adamkaak** [kbuzsaki/bingosync#250]
Hey man hope you doing great i've uploaded 9 Hitman 3 generators and added all of them in the Update_game_type.py
No changes needed from you I guess
Can you please accept my Pull request ?
https://github.com/kbuzsaki/bingosync/pull/247

**Comment by kbuzsaki** [comment]
In the future it's fine to just send a pull request, no need to open an issue separately unless you have something to discuss -- I get notifications for both :)
