### ISSUE TITLE
Horizon Zero Dawn Board New Variant

### ISSUE THREAD

**Issue by AltinCloak** [kbuzsaki/bingosync#252]
Hey, sorry to have so many updates one right after another, but I have another Variant: The Sacred Lands. https://github.com/AltinCloak/HorizonBingo/blob/main/HZD/Sacred-Land-Bingo.JSON

**Comment by AltinCloak** [comment]
New Link for the Sacred Lands variant: https://github.com/HorizonSpeedrun/HorizonBingo/blob/main/HZD/Sacred-Land-Bingo.JSON 

Also it would be nice if the `normal` variant was removed to reduce confusion

**Comment by kbuzsaki** [comment]
I added the "The Sacred Lands" variant and it's now live :)

re: renaming the existing version, it seems like that's the one that gets the most plays right now so I'm hesitant to rename it unless the name isn't descriptive. "Normal" usually refers to an average length bingo board that covers most of the game's content. Do you feel that that isn't descriptive of the current normal goal list? I'm not sure that calling it "tht1kd" will be more self-descriptive to the average user.

**Comment by AltinCloak** [comment]
`Main Game - tht1kd` would maybe be a better name. Mostly there is a more comprehensive full game board with a different methodology (for example, "Don't do X" goals) and I've heard a fair amount of confusion from the speedrunning community about that board and that sort of thing would help.
