### ISSUE TITLE
Rainbow Six Siege Bingo Board

### ISSUE THREAD

**Issue by Alive527** [kbuzsaki/bingosync#254]
I have spent 3 days learning JSON and what srlv5 is exactly just to make this. Hopefully it can help a somewhat dying game, and also add another to the bingosync list.

 1. https://pastebin.com/ipXLURjM (sorry for only one variant, as I said i spent 3 days learning JSON for this ToT)

 2. Rainbow Six Siege
 
 3. R6S
 
 Thank you for encouraging me to self learn code. Great website 10/10

**Comment by Alive527** [comment]
Ive been updating my pastebin while waiting for it to be verified, incase that makes an issue. Just making sure you know now better than later

**Comment by kbuzsaki** [comment]
Deployed :)
