### ISSUE TITLE
Windwaker Randomizer Bingo Update

### ISSUE THREAD

**Issue by BenjaminSnarky** [kbuzsaki/bingosync#255]
My windwaker randomizer bingo hasn't been updated on bingosync in a long time and its drastically different and more polished. There are lots of new people playing too so I would like to update it now so everyone has a good experience.

https://docs.google.com/document/d/19QTYCmhCUwnNHhYHgN4iytg1Hg7CHPtJAiLBIbpWTts/edit

**Comment by BenjaminSnarky** [comment]
https://pastebin.com/JDSFvxCA

**Comment by BenjaminSnarky** [comment]
https://docs.google.com/document/d/19QTYCmhCUwnNHhYHgN4iytg1Hg7CHPtJAiLBIbpWTts/edit

**Comment by kbuzsaki** [comment]
I merged https://github.com/kbuzsaki/bingosync/pull/262 which I assume obsoletes this?

Feel free to send another PR if you have more updates :)
