### ISSUE TITLE
Game Request - Elden Ring

### ISSUE THREAD

**Issue by lilaggytv** [kbuzsaki/bingosync#260]
1. Goal list - https://pastebin.com/h5Sduj3H (JSON - https://pastebin.com/kg6C0T0j)
2. Game title - Elden Ring
3. Game abbreviation - Elden Ring

Just a simple list, no SRL-style difficulty balancing necessary. Thanks!

**Comment by toejamburger** [comment]
Hey I made another list for Elden Ring, it's here if you wanna look at it: https://pastebin.com/N3u366e7

Would you want to combine our lists into one large list?

**Comment by kbuzsaki** [comment]
I've deployed this version of the goal list on the site because @lilaggytv mentioned that they wanted to use it in a tournament in https://github.com/kbuzsaki/bingosync/pull/275

I'm happy to updated with whatever merged version the two of you agree on after that.
