### ISSUE TITLE
New Game Request: Peggle Deluxe

### ISSUE THREAD

**Issue by britsha** [kbuzsaki/bingosync#263]
Put together a SRL-style goal list using the aspects required for 100% completing Peggle Deluxe which earns you the title EGM (Extreme Grand Master).

Have tested lockout with a couple other Peggle runners.

Someday would like to make a variant that adds a load of self-imposed challenges so for now this would be the "EGM" variant. 

https://pastebin.com/tp0ZU7Pp 

Name: Peggle Deluxe
Variant: EGM
Abbreviated Name: PD EGM

**Comment by kbuzsaki** [comment]
This is now live :)
