### ISSUE TITLE
New Game Request: Peggle Nights

### ISSUE THREAD

**Issue by britsha** [kbuzsaki/bingosync#264]
As well as the Peggle Deluxe request, also put together a SRL-style goal list for Peggle Nights using the aspects required for 100% completing the game, earning the title UEGM (Ultra Extreme Grand Master).

Like with Peggle Deluxe, may want to make a variant for Peggle Nights at a later date that adds a load of self-imposed challenges so for now this is the "UEGM" variant.

https://pastebin.com/gAkV2MCg

Name: Peggle Nights
Variant: UEGM
Abbreviated Name: PN UEGM

**Comment by kbuzsaki** [comment]
This is now live :)
