### ISSUE TITLE
BotW German Translation

### ISSUE THREAD

**Issue by Nintold** [kbuzsaki/bingosync#265]
Just translated the zelda_botw_english.js for a DE-Variant.
[botw_DE.txt](https://github.com/kbuzsaki/bingosync/files/10300777/botw_DE.txt)

**Comment by kbuzsaki** [comment]
Hey, I'm going to add your version of the goal list, but it looks like it's slightly different from the english version which causes the generated cards to be different: https://github.com/kbuzsaki/bingosync/blob/main/bingosync-app/generators/goal_lists/zelda_botw_english.js

Feel free to submit an updated version to correct that if you'd like.

**Comment by kbuzsaki** [comment]
Deployed :)
