### ISSUE TITLE
Game request: Hearthstone (Have a full board for it)

### ISSUE THREAD

**Issue by x9Wildcard** [kbuzsaki/bingosync#267]
Hi!
Me and my friend have been having a lot of fun with bingosync, but we had to create our custom board which took time. I want to share this to help others wanting to do the same, can so easily.
https://www.youtube.com/watch?v=Qg-a0AQKP_8&t=95s : this is a video of a popular hearthstone youtuber using bingosync in the same way me and my friend did, I think it's a worthy contender for the website!

Here is my 25 tile list:
[{
		"name": "win a classic game"
	},
	{
		"name": "freeze 7 characters in one turn"
	},
	{
		"name": "win against Sindragosa in the frozen throne solo adventure"
	},
	{
		"name": "play a dragon"
	},
	{
		"name": "kill 6 mininons using a weapon in a game"
	},
	{
		"name": "Win the tavern brawl"
	},
	{
		"name": "die to fatigue damage"
	},
	{
		"name": "Play 10 spells in one turn"
	},
	{
		"name": "Empty your hand twice in the same turn"
	},
	{
		"name": "spend 40 mana worth of spells in a game"
	},
	{
		"name": "Get lethal with a 2 cost spell"
	},
	{
		"name": "Play 4 Legendaries in one turn"
	},
	{
		"name": "Trade 5 cards in one game"
	},
	{
		"name": "Play a dragon that cost 5 or more mana"
	},
	{
		"name": "make your opponent overdraw 2 cards in one turn"
	},
	{
		"name": "Get an overkill lethal"
	},
	{
		"name": "Deal 30 damage to yourself in a game"
	},
	{
		"name": "corrupt 3 cards in a game"
	},
	{
		"name": "Play three 0 mana cards in one turn"
	},
	{
		"name": "Play the same old god twice"
	},
	{
		"name": "Heal 40 health in a game"
	},
	{
		"name": "Draw 10 cards in one turn"
	},
	{
		"name": "Win with murlocs"
	},
	{
		"name": "Play a 10 mana minion with no effect"
	},
	{
		"name": "Control 5 secrets at once"
	}
]

**Comment by kbuzsaki** [comment]
Hey, I'm glad you've been having fun with Bingosync :)

While 25 goals is the minimum necessary for a custom card, I prefer to have more than that when adding goal lists to the actual site. Please try to have at least 40-50 goals for a simple goal list, or at least 75 goals for an SRL-style goal list.

I'm closing this issue for now, feel free to reopen or file another if you'd like to add an expanded goal list.
