### ISSUE TITLE
New Game Request: Elden Ring

### ISSUE THREAD

**Issue by toejamburger** [kbuzsaki/bingosync#277]
Here's the list I came up with: https://pastebin.com/N3u366e7

Sorry it's not categorized, I don't really know enough about doing this kind of thing to do that properly I think

**Comment by kbuzsaki** [comment]
There's another game request for Elden Ring already open here: https://github.com/kbuzsaki/bingosync/issues/260
Do these lists look roughly similar or should both be added?

**Comment by toejamburger** [comment]
They look similar enough, although I think enough is different that both
could be added. Up to you I suppose.

If it matters, the main differences seem to be my list has far more
specific things that are needed, and that other list has more broad items,
if that makes sense.

**Comment by Alive527** [comment]
Maybe you can discuss with the original poster to make a combined list?

**Comment by toejamburger** [comment]
For sure, I'll look into it

**Comment by toejamburger** [comment]
Okay, so I could not seem to get ahold of the original poster, so I took
the liberty of combining our lists myself, this is the result:
https://pastebin.com/FHBuYucC

If it's a problem that I did this let me know. Their list is entirely
intact, I took any duplicates we had (there were like 5 or so) out of my
part of the list. I didn't mix them up or anything, since neither of us
made it with any kind of sorting in mind. If it matters, my list starts at
the line {"name": "Get two different full Medallions"}, so if they need to
be separated again for any reason there you go. Hope this helps.

**Comment by kbuzsaki** [comment]
I've deployed the other version of the goal list on the site because @lilaggytv mentioned that they wanted to use it in a tournament in https://github.com/kbuzsaki/bingosync/pull/275

I'm happy to updated with whatever merged version the two of you agree on after that.

**Comment by kbuzsaki** [comment]
Whoops, didn't mean to close the issue. We can keep this one open to discuss the merging.

**Comment by toejamburger** [comment]
I haven't been able to get ahold of @lilaggytv to discuss anything about merging our lists, unfortunately. You said they mentioned wanting to use their list in a tournament this month? Where/when is the tournament happening if I can ask?

**Comment by kbuzsaki** [comment]
I don't know where the tournament is being held unfortunately, they just mentioned it in their github issue. It looks like they're a youtuber / twitch streamer, so maybe you can get ahold of them via the twitter / email / discord information that they link from there?

**Comment by toejamburger** [comment]
Gotcha, I'll see if I can find them.

**Comment by lilaggytv** [comment]
Hey guys! I would prefer to not merge the lists, the set I have submitted has been playtested and refined quite a bit at this point and is now being used for an ongoing bingo league. Even outside of the league, I'd be concerned with it being properly balanced if we were to merge it. Hope you understand, I've put a lot of work into it.

Speaking of which, not sure when @kbuzsaki added my list to the site but I've been editing the pastebin I linked in #260 with updates/changes pretty regularly. I'm now done with changes for the time being if they wanted to update/finalize it: https://pastebin.com/kg6C0T0j

If @toejamburger wants to add their list as a separate set on the site that's fine with me, though it might be a little confusing for people. Obviously that's ultimately up to @kbuzsaki to decide whatever they want to do with their site.

Thanks guys! Sorry for not getting in contact sooner.

**Comment by toejamburger** [comment]
I guess I could remake my list for a randomizer? A bunch of the goals could already fit a randomizer anyway, so I'd just have to change some of the ones that would be unreasonable to do when items aren't in proper places.

Should I go ahead and do that or do y'all want to just put my list into a different category or something?

**Comment by toejamburger** [comment]
I know I asked a few hours ago, but I did go ahead and make a few changes that seem like they would make it easier for doing an Item randomizer with it if that's the way y'all want to go ahead, here's the new version https://pastebin.com/FESMMXnH
