### ISSUE TITLE
New Game Request: Spyro the Dragon Reignited

### ISSUE THREAD

**Issue by goosehero** [kbuzsaki/bingosync#280]
I know that there is a bingo board for the original spyro the dragon. I would like to request one for specifically the reignited version of the game. 

1. simple goal list
 https://pastebin.com/MEq9sirG
2. Game Name: Spyro the Dragon Reignited
3. Abbreviated Name: SRT1

Thanks in advance!

**Comment by kbuzsaki** [comment]
This is now live :)
