### ISSUE TITLE
Is there a discord server for this?

### ISSUE THREAD

**Issue by That-Ski-Freak** [kbuzsaki/bingosync#284]
Sorry to ask within an issue if this isn't the place, but is there a discord server for bingosync? Maybe I have just become accustomed to every internet sub community having a discord or forum or place for users to type but I couldn't find one.

**Comment by kbuzsaki** [comment]
No, there is not a discord server for bingosync generally, and I'm not interested in having one at this time.

Bingosync is just a platform though, and many speedrunning communities have discord servers for their specific games and bingo varieties :)
