### ISSUE TITLE
New Game Request: Kirby and the Forgotten Land

### ISSUE THREAD

**Issue by DarkRiolu27** [kbuzsaki/bingosync#290]
Hello, I made a list of bingo goals here: https://pastebin.com/5K0XRNTx

It's for Kirby and the Forgotten Land, KFL for short. I don't have any experience making bingo lists, so let me know if I need to fix the formatting.

**Comment by kbuzsaki** [comment]
This is now live :)

**Comment by DarkRiolu27** [comment]
Thanks!
