### ISSUE TITLE
Splatoon 3 weapon Bingo

### ISSUE THREAD

**Issue by AwesBlaze** [kbuzsaki/bingosync#292]
Blaster 
Clash Blaster 
Clash Blaster Neo 
Luna Blaster 
Luna Blaster Neo 
Range Blaster 
Rapid Blaster 
Rapid Blaster Deco 
Rapid Blaster Pro 
Splat Brella 
Tenta Brella 
Undercover Brella 
Inkbrush 
Inkbrush Nouveau 
Octobrush 
Bamboozler 14 Mk I 
Classic Squiffer 
E-Liter 4K 
E-Liter 4K Scope 
Goo Tuber 
Snipewriter 5H 
Splat Charger 
Splatterscope 
Z+F Splat Charger 
Z+F Splatterscope 
Dapple Dualies 
Dapple Dualies Nouveau 
Dualie Squelchers 
Glooga Dualies 
Splat Dualies 
Dark Tetra Dualies 
Big Swig Roller 
Carbon Roller 
Carbon Roller Deco 
Dynamo Roller 
Splat Roller 
Krak-On Roller 
Flingza Roller 
.52 Gal
.96 Gal
.96 Gal Deco
Aerospray MG
Aerospray RG
Jet Squelcher 
Custom Jet Squelcher
Splattershot Jr.
Custom Splattershot Jr.
Forge Splattershot Pro
Splattershot Pro
H-3 Nozzlenose
L-3 Nozzlenose
L-3 Nozzlenose D
Splash-o-matic
Neo Splash-o-matic
N-Zap ‘85
N-Zap ‘89
Squeezer
Splattershot
Hero Shot Replica
Splattershot Nova
Sploosh-o-matic
Tentatek Splattershot
Neo Sploosh-o-matic
Bloblobber
Explosher 
Slosher
Slosher Deco
Tri-Slosher
Tri-Slosher Nouveau
Sloshing Machine
Splatana Stamper
Splatana Wiper
Ballpoint Splatling
Hydra Splatling
Mini Splatling
Zink Mini Splatling
Heavy Splatling
Nautilus 47
REEF-LUX 450
Tri-Stringer
S Blast ‘92
Painbrush
H-3 Nozzlenose D
Rapid Blaster Pro Deco
Light Tetra Dualies
Tenta Sorella Brella
Annaki Splattershot Nova
Splatana Wiper Deco
Custom Dualie Squelchers
Heavy Splatling Deco
Big Swig Roller Express

I also love what you are doing, and will be using this super often. I also know a lot of people who like your system, so thank you in advance! (Also, sorry for not being in paste bin, I don’t know how to work it)

**Comment by AwesBlaze** [comment]
@kbuzsaki it has been a month and I just wanted to make sure updates to the system are still being made

**Comment by kbuzsaki** [comment]
Yes, I'm still making updates but as you can see they're on a very irregular schedule, haha. Your game will be added shortly.

**Comment by kbuzsaki** [comment]
This is now live :)

**Comment by kbuzsaki** [comment]
Please file another GitHub issue or pull request with the new goal list to use :)
