### ISSUE TITLE
Separate Undertale Lists?

### ISSUE THREAD

**Issue by Alive527** [kbuzsaki/bingosync#294]
https://pastebin.com/2GF4fenj#5FzW5jqb - the original undertale goal list

I was wondering who made the original list, and if I would be able to make separate lists for the main pathways of the game
The current list is only fitting for a neutral run, where you can both kill and spare, but I was wondering if I could make a pacifist and genocide list as well, despite not having made the original list?

Ill try making some lists regardless, but I'll wait to submit until I know it would be okay

**Comment by kbuzsaki** [comment]
Sure, you can submit specialized lists that I can put in addition to the current list.

For example, the current list could be "Normal" or "all modes", and the others could have a route name

**Comment by Alive527** [comment]
Well, with the three paths of the game being Pacifist, Genocide, and Neutral, the current list easily fits Neutral route, so we could name all 3 lists accordingly to minimalize any confusion. Thank you!

**Comment by Alive527** [comment]
Im gonna close this issue now. Ive made the genocide bingo, and im play-testing it currently. Should be uploaded separately tomorrow :D
