### ISSUE TITLE
Undertale Genocide Variant

### ISSUE THREAD

**Issue by Alive527** [kbuzsaki/bingosync#296]
https://pastebin.com/nNYkRevb - JavaScrpit (Idk if it would be easier with this or not but i copy pasted the old list right from the code)
https://pastebin.com/zBTV8FsX - JSON (if you want this instead)

Thank you for letting me make these variants. Ill get to work on the Pacifist variant soon!

**Comment by kbuzsaki** [comment]
This is now live :)
