### ISSUE TITLE
new game request: King of the castle 2 variants 

### ISSUE THREAD

**Issue by Thedmpanda** [kbuzsaki/bingosync#297]
HI can you please add King of the castle to bingosync
Short name: KotC

The attached files work in the custom advanced option

Variant 1: multiple playthroughs
[Kotc Multiple playthrough.txt](https://github.com/kbuzsaki/bingosync/files/11415053/Kotc.Multiple.playthrough.txt)

Varianrt 2: single playthrough (slr v5)
[KOTC single playthrough.txt](https://github.com/kbuzsaki/bingosync/files/11415051/KOTC.single.playthrough.txt)

**Comment by kbuzsaki** [comment]
This is now live :)
