### ISSUE TITLE
Make SMM2 a bit more stream friendly

### ISSUE THREAD

**Issue by Suparyn** [kbuzsaki/bingosync#300]
Sorry if this sounds like a prude, but could you delete the word "fucking" from the Super Mario Maker 2 box of "Too many fucking spikes." I get it, they hate spikes, but I want to keep it kid friendly and adding fucking doesn't add anything. Hopefully it's an easy fix, so thank you!

**Comment by haylau** [comment]
Made the change in #301 for ya. Don't know if it'll get merged in or not.
