### ISSUE TITLE
New Game Request - Destiny 2 

### ISSUE THREAD

**Issue by STOERSE** [kbuzsaki/bingosync#302]
Hello, I am making this post with hopes that I could have Destiny 2 Added to the list of available game Generators. 

1.) Goal/ Generator: https://pastebin.com/jNshK0xR
2.) The name you'd like (for the room creation dropdown): Destiny 2
3.) The abbreviated name you'd like, ideally no more than 10-12 characters (for the rooms list) : D2

I hope that everything was done correctly! Thank you for your time!

**Comment by STOERSE** [comment]
Any possible updates for this? If there is any other way to get the Generator set up? please let me know!

**Comment by kbuzsaki** [comment]
You should be able to use the "Custom SRL v5" game and variant to create games with this list until I put it up for real.

**Comment by STOERSE** [comment]
> You should be able to use the "Custom SRL v5" game and variant to create games with this list until I put it up for real.

Roger. I see how that works now. I appreciate the reply and your time!

**Comment by kbuzsaki** [comment]
This is now live :)
