### ISSUE TITLE
New Game Request - PikuNiku

### ISSUE THREAD

**Issue by GreyFather** [kbuzsaki/bingosync#304]
Short Indie-Game designed by Sectordub. The game is only 3 hours long and 6 hours long for 100% completion.
59 Goals List:
[{"name": "Get Flower Hat"},
 {“name”: “Get Watering Hat”},
 {“name”: “Get all hats”}, 
 {"name": "Collect 25 coins"},
 {"name": "Collect 50 coins"},
 {“name”: “Collect 75 coins”},
 {"name": "Water 5 flowers"},
 {“name”: “Water 10 flowers”},
 {"name": "Watch 2 bugs dance"},
 {"name": "Watch 4 bugs dance"},
 {"name": "Get Swag"},
 {"name": "Find rock 3 times"},
 {“name”: “Find 4 Trophies”},
 {“name”: “Find 6 Trophies”},
 {“name”: “Find 8 Trophies”},
 {“name”: “Get 10 trophies”},
 {“name”: “Get 12 Trophies”},
 {"name": "Dig out all blocks in Pikdug"},
 {"name": "Defeat wood robot no deaths"},
 {“name”: “Defeat corn robot no deaths”}
 {“name”: “Defeat water robot no deaths”},
 {"name": "Kick a single Npc 20 times"},
 {"name": "Find Ernie The Worm"},
 {"name": "Kill the Demon Toast"},
 {"name": "Score a 90% or higher in the dancing game"},
 {“name”: “Score a 0% on the dancing game”},
 {"name": "Purchase the X-Ray Goggles"},
 {"name": "Save the 2 baby birds"},
 {"name": "Buy the beast stuffed animal"},
 {"name": "Win 3-2 in a game of Baskicks"},
 {"name": "Draw the scarecrow's face"},
 {"name": "Collect 2 Apples"},
 {"name": "Beast mask cave all coins"},
 {“name”: “Golden tooth cave all coins”},
 {"name": "Get the Piku on beach trophy"},
 {“name”: “The resistance trophy”},
 {"name": "The demonic toast trophy"},
 {“name”: “The hidden rock trophy”},
 {"name": "Do a scale on the piano"},
 {"name": "Say no to helping rebuild bridge"},
 {"name": "Dunk yourself in the basketball hoop"},
 {"name": "Buy the postcard"},
 {"name": "Smash all the Pottery"},
 {"name": "Scare 5 civilians with the beast mask"},
 {"name": "See 5 security cameras"},
 {"name": "Die to popcorn in the lava race"},
 {"name": "Enter a vent"},
 {"name": "Kill yourself with a laser"},
 {"name": "Get caught in the sneak scene"},
 {"name": "Beat the game"},
 {“name”: “Kick Mr. Sunshine to the left”},
 {“name”: “Play the worm’s video game”},
 {"name": "Get a score above 10 in the worm's video game"},
 {“name”: “Turn rebel base power back on”}, 
 {“name”: “Obtain Some Arms”},
 {“name”: “Draw on the forest tree’s face”}]

**Comment by kbuzsaki** [comment]
This is now live :)
