### ISSUE TITLE
New Game Request: Harvest Moon Back to Nature

### ISSUE THREAD

**Issue by xnadgg** [kbuzsaki/bingosync#307]
Hello,
I wanted to add **Harvest Moon: Back to Nature** to the available list.

I have created simple and tiered list as follows, and I want to add both of them. Is it possible to split these into 2 variants? Or maybe it's easier to do it as 2 separate games?

#### Harvest Moon Back to Nature (simple list)
hmbtn_simple
https://pastebin.com/h89pf41G

#### Harvest Moon Back to Nature (tiered list)
hmbtn_tiered
https://pastebin.com/KGkNguCj

The simple list should theoretically be faster since there are quite a number of progressive goals that can be completed together, so it would be useful for shorter runs.

The tiered list is designed to run longer with variety of tasks in a single line.

For future collaborators: feel free to discuss the list with me at [discord/xnad]

**Comment by kbuzsaki** [comment]
This is now live :)
