### ISSUE TITLE
New Game Request - Days Gone

### ISSUE THREAD

**Issue by meowingogre** [kbuzsaki/bingosync#308]
Hello!
I am hoping to add Days Gone to the list of game generators. 
This is usable with the SRL v5 game.

1.) Goal/ Generator: https://pastebin.com/Sh7AMNhA
2.) The name you'd like (for the room creation dropdown): Days Gone
3.) The abbreviated name you'd like, ideally no more than 10-12 characters (for the rooms list) : DG

Let me know if there is anything else that would be needed.

Thank you!

**Comment by kbuzsaki** [comment]
This is now live :)
