### ISSUE TITLE
New Game Request - Pseudoregalia

### ISSUE THREAD

**Issue by Cupcaeke** [kbuzsaki/bingosync#309]
Heya! I'm here representing the PSRG community! We've come up with this goal list and would love to see it on bingosync!

    The generator or goal list you'd like to use: **https://pastebin.com/cZrWhQUV**
    The name you'd like (for the room creation dropdown): **Pseudoregalia**
    The abbreviated name you'd like, ideally no more than 10-12 characters (for the rooms list): **PSRG**

Let me know if you need anything else!

**Comment by kbuzsaki** [comment]
This is now live :)
