### ISSUE TITLE
New Game Request - WWE Supercard

### ISSUE THREAD

**Issue by CS50Chaosnm** [kbuzsaki/bingosync#310]
Hello, Got a bingo board onto speedruntools and would love if it could also be hosted here for races as well! 

The generator or goal list you'd like to use: **https://pastebin.com/c54WaEZb**
The name you'd like (for the room creation dropdown): **WWE Supercard**
The abbreviated name you'd like, ideally no more than 10-12 characters (for the rooms list): **WWE SC**

Thanks! This game gets a new season every november, and some of the misisons will need to be updated as a result. It's only a few missions [6] and I have listed them, idk if editing the pastebin at the time would be enough to change them or not.

**Comment by kbuzsaki** [comment]
This is now live :)
