### ISSUE TITLE
New Game Request: Demoncrawl

### ISSUE THREAD

**Issue by SnageTheSnakeMage** [kbuzsaki/bingosync#311]
Hello, I've been interested in this minesweeper roguelike and recently tried to start a new speedrun category that I thought would be a good bingo board but I was unhappy with custom's 25 requirement as the bingo board I had in mind has 36 entries, so here's a SRLv5 goal list and details

The generator or goal list you'd like to use: https://pastebin.com/ZFZd9mhX
The name you'd like (for the room creation dropdown): Demoncrawl
The abbreviated name you'd like, ideally no more than 10-12 characters (for the rooms list): DEMNCR

Thank you so much! The game might update with new masteries(the things I'm using for the goal list) but if that happens I'll make a new issue to update my request. please contact me if there is any problem or inconsistency with the pastebin's JSON

**Comment by kbuzsaki** [comment]
SRL v5 needs exactly 25 tiers (though each tier can and should have more than 1 goal). That means that your current list doesn't have enough tiers :)

"Custom Randomized" allows you to add more than 25 goals and will randomly choose among them. I've converted your goal list into that kind of simple randomized board and will add it shortly.

**Comment by kbuzsaki** [comment]
This is now live :)
