### ISSUE TITLE
New Game Request: Pummel Party

### ISSUE THREAD

**Issue by MadamMateria** [kbuzsaki/bingosync#315]
Got a new game request, I hope I've done all of this right for the SRL format? If I've done something wrong, let me know and I can fix it up (hopefully).

The generator/goal list: https://pastebin.com/bd6d4kpE
Dropdown Name: **Pummel Party**
Abbreviated Name: **Pum Party**

Assuming I've done everything right, thank you kindly! ^_^ And a keep up the good work!

**Comment by kbuzsaki** [comment]
This is now live :)

**Comment by MadamMateria** [comment]
Oh, cool. Thanks!
