### ISSUE TITLE
New Game Request: Dark and Darker

### ISSUE THREAD

**Issue by gungyvt** [kbuzsaki/bingosync#317]
https://pastebin.com/7VKeaXf4

I think I understood the instructions for making this list properly. I was just surprised no one else had made or requested this yet, so I gave it a shot myself.

EDIT: I did not fully understand the instructions and apparently miscounted how many tiers I had made (learned I could test the text in the custom SRL, it didn't work). Also, content patch is coming in less than a week, so I'll be updating this post with a new pastebin link soon after that.

**Comment by kbuzsaki** [comment]
It looks like this pastebin still has only 20 goals so I can't add it, please update it and then reply back :)

**Comment by gungyvt** [comment]
I honestly haven't even thought much about this in the past 8 months and I can't find where to go to delete my post here, so I'm just gonna abandon the idea and mark this as closed (if I'm doing things right).
