### ISSUE TITLE
New Game Request: Metal Gear Solid: The Twin Snakes

### ISSUE THREAD

**Issue by NickRPGreen** [kbuzsaki/bingosync#319]
Hi. I'm hoping to have Metal Gear Solid: The Twin Snakes added please? 

js file available here:
https://pastebin.com/XqqdA4uu

Name: Metal Gear Solid: The Twin Snakes

Abbrev: mgs-tts

Thanks!

**Comment by kbuzsaki** [comment]
This is now live :)
