### ISSUE TITLE
synerGen: minor issues

### ISSUE THREAD

**Issue by ManicJamie** [kbuzsaki/bingosync#320]
2 of the matrix transformations performed on the base matrix in synerGen are problematic.

`inverse(t)` doesn't mutate t or return s, hence affecting nothing. As rotate relies on an `inverse`, this turns rotate into a second reflection. This cuts down the potential magic square permutations eightfold.

**Comment by kbuzsaki** [comment]
Hey, thanks for flagging the issue! I didn't write the synerGen generator so I'm not familiar with it's implementation. Maybe @asheevee can comment?

I'm also cognizant of the fact that changing a base generator implementation like this can destabilize card generation for all of the communities that are using it (and might e.g. have events in progress) so I'm going to tread carefully when making edits.

**Comment by asheevee** [comment]
I'll take a look at it! I haven't touched the thing in years it feels like, and it's 100% possible I just forgot a return command somewhere.

**Comment by kbuzsaki** [comment]
@asheevee's fix is now live :)
