### ISSUE TITLE
New Game/Generator Request: Pokemon Infinite Fusion

### ISSUE THREAD

**Issue by Alymra** [kbuzsaki/bingosync#321]
Greetings kbuzsaki and team,

Requesting a new game/generator to be added to bingosync for Pokemon Infinite Fusion.

Here's the JSON: https://pastebin.com/cShNsf05
The name you'd like (for the room creation dropdown): Pokemon Infinite Fusion
The abbreviated name you'd like, ideally no more than 10-12 characters (for the rooms list): PIF Bingo

This is my first time doing something like this so if there's any issues you see please let me know. I also had a question on if it was possible to exclude goals from a board entirely based on if one is chosen by the system. An example would be "Complete 5 Hotel Quests" and "Complete 15 Hotel Quests" wouldn't show up on the board if "Complete 10 Hotel Quests" shows up. If this isn't possible then that's fine, it could lead to some interesting game dynamics in a race setting.

Thank you for all that you do!

**Comment by kbuzsaki** [comment]
This is now live :)

**Comment by kbuzsaki** [comment]
Ah, I just saw your blackout request. I'll update that and push it again with the next batch.

**Comment by kbuzsaki** [comment]
The blackout fix is now live :)

**Comment by Alymra** [comment]
Thank you so much for getting this taken care of! It is greatly appreciated!

-Alymra
