### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by thulin82** [kbuzsaki/bingosync#323]
Is this considered a dead project?

Even though the website is up, there hasn't been any contributions since the 25th of feb (2023)...

**Comment by kbuzsaki** [comment]
I'm not currently actively developing for the site but I am committed to keeping it running and occasionally adding new game requests.

If there's a game that you'd like to try out that doesn't currently have a goal list on the site you're welcome to use the "Custom" game type and variants to have the site randomize a custom list of goals for you. 

If you're looking for additional features I believe there's also a "Bingosync+" browser extension that adds some, though I haven't used it myself.
