### ISSUE TITLE
New Game Request: Apex Legends

### ISSUE THREAD

**Issue by HasmanC** [kbuzsaki/bingosync#324]
Hi am currently using custom to run this with my mate thought it would be fun for everyone
format:
queue with each other so 2 or 3 player

I have already come up with 75 goals written below so just needs adding

{"name": "kill with ultimate"}, | {"name": "kill with tactical"}, | {"name": "kill with fully kited mozambique"},
{"name": "no scope with sentinel"}, | {"name": "non conventional kill e.g nade impact damage"}, | {"name": "kill with fully kitted"}, {"name": "kill teammate"}, | {"name": "nade kill"}, | {"name": "1 mag someone"},
{"name": "donate care pack weapon(give to enemy team)"}, | {"name": "arc stick"}, | {"name": "revive teammate"},
{"name": "no evo kill"}, | {"name": "3x finisher in 1 game"}, | {"name": "respawn teammate"},
{"name": "melee kill"}, | {"name": "get red with no switch"}, | {"name": "spawn camp (kill fresh respawn)"},
{"name": "kill with red weapon"}, | {"name": "2k dmg"}, | {"name": "duo wipe without teammate"},
{"name": "kill with 3 diff guns in 1 game"}, | {"name": "5x kills 1 game"}, | {"name": "scan 3 beacons"},
{"name": "pistol kill"}, | {"name": "3 assists 1 game"}, | {"name": "destroy a trident"},
{"name": "2x iron sight kill"}, | {"name": "kill champion"}, | {"name": "become kill leader"},
{"name": "kill kill leader"}, | {"name": "kill dragon thing"}, | {"name": "teammate takes zone damage"},
{"name": "gold bag"}, | {"name": "gold helm"}, | {"name": "gold knockdown"},
{"name": "gold armour"}, | {"name": "kill bang with digi (Checkmate)"}, | {"name": "kill fuse with nade"},
{"name": "use any survival slot item"}, | {"name": "20 cells"}, | {"name": "12 syringes"},
{"name": "6 med kits"}, | {"name": "8 batts"}, | {"name": "3 phoenix"},
{"name": "1 of every nade"}, | {"name": "6 nades"}, | {"name": "full inv of ammo(full stacks)"},
{"name": "craft a gun"}, | {"name": "collect 5 mat barrels"}, | {"name": "lmg hipfire kill"},
{"name": "2 ult accels"}, | {"name": "kill with 3 diff legends"}, | {"name": "kill any support"},
{"name": "kill any skirmisher"}, | {"name": "kill any assault"}, | {"name": "kill any control"},
{"name": "kill any recon"}, | {"name": "scan 3 legends at once"}, | {"name": "top 5 no healing(tie goes to kills)"},
{"name": "kill headshots only(no sniper)"}, | {"name": "no headshot game (2 cred min)"}, | {"name": "activate vault / raid armoury / caustic treatment loot/ big maude"},
{"name": "2x shotgun kills 1 game"}, | {"name": "3x smg kills 1 game"}, | {"name": "3x Ar kills 1 game"},
{"name": "3x lmg kills 1 game"}, | {"name": "2x marksman kills 1 game"}, | {"name": "2x sniper kills 1 game"},
{"name": "smg kill no hit(100 min dmg)"}, | {"name": "skynade hit 10 dmg min"}, | {"name": "kill with any multifire in single mode"},
{"name": "kill with same gun 2 games in a row"}, | {"name": "drop same building as hostile"}, | {"name": "use any hop up"},

Please consider 
Thanks,
HasmanC

**Comment by kbuzsaki** [comment]
Hi there, this goal list looks like it has some formatting errors (the `|` characters sprinkled throughout) and seems to have inconsistent capitalization and abbreviations. I'm glad you're having fun playing with your friends, but I think this list might need a bit more polish before publishing :)

I'm going to close this issue for now, please reopen if you're still interested in adding the game and have a polished up version of the list.
