### ISSUE TITLE
Request: Game Update - Threads of Fate

### ISSUE THREAD

**Issue by shinytentacruel** [kbuzsaki/bingosync#325]
Hello,

I would like a slight update to the list of items for the game Threads of Fate.

Here is a pastebin link to the updated list:
https://pastebin.com/WeFJhSPT

To verify change is successful you can identify that "Drown in lava 10 times" is changed to "Drown in lava 3 times".

Thank you,
Shinytentacruel

**Comment by kbuzsaki** [comment]
This is now live :)
