### ISSUE TITLE
New game request: Horizon Forbidden West & Burning Shores DLC

### ISSUE THREAD

**Issue by Nicopico2014** [kbuzsaki/bingosync#327]
Hello, I was hoping to ask the Bingosync team to add Horizon Forbidden West to the game pile. You all seem quite busy, so if I can help with adding this game by giving you all the quest/errand titles, NPCs, locations, weapons, achievements, or whatever it is you need, I'm willing to do so. Anyways, thank you for giving this a read and thank you for making such an awesome website!

**Comment by AltinCloak** [comment]
I'm working on that with the Horizon Speedrunning community, over at https://github.com/HorizonSpeedrun/HorizonBingo

**Comment by kbuzsaki** [comment]
This is now live, added this goal list: https://github.com/HorizonSpeedrun/HorizonBingo/blob/f686fcc23c45b07ffa011fe9bdf67cced0f1c8f0/HFW/bingo-maingame.JSON
