### ISSUE TITLE
bingosync.com is down with 504 and 502 errors.

### ISSUE THREAD

**Issue by hitgub043** [kbuzsaki/bingosync#328]
Sorry if this is a bad place to post this, but I found that the bingosync website is currently down. The 504 and 502 errors seem to be server-side. I was able to connect once while occasionally refreshing, but I couldn't create a room without getting the error again. I did see that some rooms were still listed at that time, so this issue may not be affecting everyone.

On a somewhat related note, is there a relatively easy way to host this app locally and connect peer-to-peer with another user? I just like having the option in case there's an outage or the project is ever taken offline.

**Comment by kbuzsaki** [comment]
Thanks for the report. I'm not sure what the cause was but I restarted the server and it seems to have recovered. Please reopen/file another issue if you see problems again.
