### ISSUE TITLE
Connection Issue: Can't access Bingosync

### ISSUE THREAD

**Issue by Doctor-Zer0** [kbuzsaki/bingosync#329]
Whether this is a good place to post this or if this is well-known are both well past my knowledge. I found no other reasonable place to publicize a Bingosync-related issue without access to the website.
Me and a friend of mine both tried to access Bingosync at bingosync.com, and both of us were met with a similar error: the website not loading, or "bingosync.com took too long to respond" being displayed with suggested actions along the lines of checking internet connection and proxy servers, editing the firewall, and so on. Browser change did nothing; same problem on every single one.
Any help or clarification would be greatly appreciated.

Tested browsers: Opera GX, Microsoft Edge, Google Chrome

**Comment by Doctor-Zer0** [comment]
Fixed itself after a while. Not sure how or why.

**Comment by kbuzsaki** [comment]
I rebooted the server after seeing this issue, thanks for the report.
