### ISSUE TITLE
New Game Request: Infinite Craft

### ISSUE THREAD

**Issue by jareddishman** [kbuzsaki/bingosync#330]
Goal List: https://pastebin.com/4whxyUtW

Name: Infinite Craft

Abbreviation: Inf Craft

Goal list is 1812 items scraped from https://www.geekyhobbies.com/infinite-craft-word-crafting-guide/ on 02/17/2024

**Comment by jareddishman** [comment]
Updated list as of 03/12/2024 (2459 items): https://pastebin.com/9kkXt1w6

**Comment by kbuzsaki** [comment]
This is now live :)
