### ISSUE TITLE
New game request : Mario Kart Wii

### ISSUE THREAD

**Issue by GalDen01** [kbuzsaki/bingosync#335]
Hello, I am currently preparing a bingo for Mario Kart Wii Online, and I wonder if it could be added to the website for everyone to use and play with. I don't know if I gave enough objectives to aim at, probably not, hence why i wonder if I could get some feedback on my objectives for now.
Here's the link to a pastebin with every one of them : https://pastebin.com/9RjAGV7g
I will keep updating the pastebin with more and more objectives, let me know if you would be willing to add Mario Kart Wii on the website.

**Comment by kbuzsaki** [comment]
This is now live :)
