### ISSUE TITLE
Splatoon 3 weapon bingo update

### ISSUE THREAD

**Issue by AwesBlaze** [kbuzsaki/bingosync#339]
Adds additional weapons to the randomized list:

.52 Gal Deco
Ballpoint Splatling Nouveau
Bamboozler 14 Mk II
Bloblobber Deco
Charcoal Decavitator
Custom Blaster
Custom Douser Dualies FF
Custom E-Liter 4K
Custom E-Liter 4K scope
Custom Explosher
Custom Goo Tuber
Custom Hydra Splatling
Custom Range Blaster
Custom Wellstring V
Douser Dualies FF
Dread Wringer
Dread Wringer D
Enperry Splat Dualies
Foil Flingza Roller
Foil Squeezer
Glooga Dualies Deco
Gold Dynamo Roller
Heavy Edit Splatling
Heavy Edit Splatling Nouveau
Inkline Tri-Stringer
Mint Decavitator
Nautilus 79
New Squiffer
Painbrush Nouveau
Recycled Brella 24 Mk I
Recycled Brella 24 Mk II
REEF-LUX 450 Deco
S-BLAST ‘91
Sloshing Machine Neo
Snipewriter 5B
Sorella Brella
Splatana Stamper Nouveau
Undercover Sorella Brella
Wellstring V

Thank you for the help with the previous task as well! I truly appreciate how much you are doing with this really awesome site. Keep up the good work!

**Comment by kbuzsaki** [comment]
This list looks shorter than the one you submitted previously -- is it the full new list that you want to use? 

Please make sure you submit the entire list you want to use each time, it makes it much easier for me to perform the updates :)

**Comment by AwesBlaze** [comment]
this is in addition to the list already sent. THis is not a seperate list if that is the confusion

**Comment by kbuzsaki** [comment]
Please send the list you'd like in its entirety. My tooling for performing updates does not handle partial lists.

**Comment by AwesBlaze** [comment]
will do:

.52 Gal Deco
Ballpoint Splatling Nouveau
Bamboozler 14 Mk II
Bloblobber Deco
Charcoal Decavitator
Custom Blaster
Custom Douser Dualies FF
Custom E-Liter 4K
Custom E-Liter 4K scope
Custom Explosher
Custom Goo Tuber
Custom Hydra Splatling
Custom Range Blaster
Custom Wellstring V
Douser Dualies FF
Dread Wringer
Dread Wringer D
Enperry Splat Dualies
Foil Flingza Roller
Foil Squeezer
Glooga Dualies Deco
Gold Dynamo Roller
Heavy Edit Splatling
Heavy Edit Splatling Nouveau
Inkline Tri-Stringer
Mint Decavitator
Nautilus 79
New Squiffer
Painbrush Nouveau
Recycled Brella 24 Mk I
Recycled Brella 24 Mk II
REEF-LUX 450 Deco
S-BLAST ‘91
Sloshing Machine Neo
Snipewriter 5B
Sorella Brella
Splatana Stamper Nouveau
Undercover Sorella Brella
Wellstring V
Blaster
Clash Blaster
Clash Blaster Neo
Luna Blaster
Luna Blaster Neo
Range Blaster
Rapid Blaster
Rapid Blaster Deco
Rapid Blaster Pro
Splat Brella
Tenta Brella
Undercover Brella
Inkbrush
Inkbrush Nouveau
Octobrush
Bamboozler 14 Mk I
Classic Squiffer
E-Liter 4K
E-Liter 4K Scope
Goo Tuber
Snipewriter 5H
Splat Charger
Splatterscope
Z+F Splat Charger
Z+F Splatterscope
Dapple Dualies
Dapple Dualies Nouveau
Dualie Squelchers
Glooga Dualies
Splat Dualies
Dark Tetra Dualies
Big Swig Roller
Carbon Roller
Carbon Roller Deco
Dynamo Roller
Splat Roller
Krak-On Roller
Flingza Roller
.52 Gal
.96 Gal
.96 Gal Deco
Aerospray MG
Aerospray RG
Jet Squelcher
Custom Jet Squelcher
Splattershot Jr.
Custom Splattershot Jr.
Forge Splattershot Pro
Splattershot Pro
H-3 Nozzlenose
L-3 Nozzlenose
L-3 Nozzlenose D
Splash-o-matic
Neo Splash-o-matic
N-Zap ‘85
N-Zap ‘89
Squeezer
Splattershot
Hero Shot Replica
Splattershot Nova
Sploosh-o-matic
Tentatek Splattershot
Neo Sploosh-o-matic
Bloblobber
Explosher
Slosher
Slosher Deco
Tri-Slosher
Tri-Slosher Nouveau
Sloshing Machine
Splatana Stamper
Splatana Wiper
Ballpoint Splatling
Hydra Splatling
Mini Splatling
Zink Mini Splatling
Heavy Splatling
Nautilus 47
REEF-LUX 450
Tri-Stringer
S Blast ‘92
Painbrush
H-3 Nozzlenose D
Rapid Blaster Pro Deco
Light Tetra Dualies
Tenta Sorella Brella
Annaki Splattershot Nova
Splatana Wiper Deco
Custom Dualie Squelchers
Heavy Splatling Deco
Big Swig Roller Express

**Comment by kbuzsaki** [comment]
This is now live :)
