### ISSUE TITLE
Request for new Hollow Knight generator

### ISSUE THREAD

**Issue by adyn99hk** [kbuzsaki/bingosync#342]
Hello Kyle!

I would like to make a request for the addition of a new Hollow Knight generator onto Bingosync.

The file: 
[hollow_knight_item_rando_blackout_generator.txt](https://github.com/user-attachments/files/15778502/hollow_knight_item_rando_blackout_generator.txt) 
(didn't let me attach a .js, so it's there as a .txt that's supposed to be a .js just like the other generator).
Dropdown name: Item Randomizer - Blackout
Abbreviated name: HK Rando BO

This is based on the current item rando generator, somewhat reworked, reworded, changed with some new stuff added
to make it a bit more fitting for HK blackout races. 
I (and other people from the community) would like it this was a separate option from the current main item rando generator,
in addition to it, not as a replacement of course.

**Comment by kbuzsaki** [comment]
This is now live :)

**Comment by adyn99hk** [comment]
Thank you very much! ^^
