### ISSUE TITLE
New Game Request: SMB3R Open World

### ISSUE THREAD

**Issue by t0zzle** [kbuzsaki/bingosync#353]
The generator or goal list you'd like to use: See attached txt files
The name you'd like: Super Mario Bros. 3 Randomizer - Open World
The abbreviated name you'd like: SMB3R Open World

**Variant:** 
M-A-R-I-O
[SMB3R Bingo.txt](https://github.com/user-attachments/files/16326604/SMB3R.Bingo.txt)

Game Modes:
Regular Bingo
Multi-Bingo
Lockout

**Variant:** 
Race to W8
[SMB3R Bingo (no bowser).txt](https://github.com/user-attachments/files/16326605/SMB3R.Bingo.no.bowser.txt)
Game Modes:
Regular Bingo
Multi-Bingo

Thank you for your help!

**Comment by kbuzsaki** [comment]
This is now up on the site :)

**Comment by t0zzle** [comment]
YAY! The community is SO excited! We've made some tweaks to the cards which
I will submit as an update shortly.

THANK YOU SO MUCH!
