### ISSUE TITLE
New Game Request - Sky: Children of the Light

### ISSUE THREAD

**Issue by iridazed** [kbuzsaki/bingosync#356]
The generator or goal list you'd like to use: 
[Bingosync-Goal-List-Sky-Children-of-the-Light.txt](https://github.com/user-attachments/files/16518822/Bingosync-Goal-List-Sky-Children-of-the-Light.txt)

The name you'd like (for the room creation dropdown):
Sky: Children of the Light

The abbreviated name you'd like, ideally no more than 10-12 characters (for the rooms list):
Sky: COTL

This list was created by Iridaze and WormsOk.

Thank you!

**Comment by kbuzsaki** [comment]
This is now up on the site :)
