### ISSUE TITLE
New game request: Noita

### ISSUE THREAD

**Issue by Yolksyb13** [kbuzsaki/bingosync#359]
Goal list: https://docs.google.com/spreadsheets/d/1nNMj2F2o-47UOlXZ8N5V9FZtIPmf_quLc-XEh_Teegs/edit?gid=0#gid=0
Name: Noita
Abbreviated: Not needed

Edit: Depreciated, look at New Variant of Noita board by vexilus
Thank you for the effort!

**Comment by kbuzsaki** [comment]
Closing as requested in favor of #361
