### ISSUE TITLE
How to Test synerGen?

### ISSUE THREAD

**Issue by gunpowder77** [kbuzsaki/bingosync#363]
How do I test a synerGen formatted goalset without literally opening a pull request and testing in production.

**Comment by kbuzsaki** [comment]
The way to do this right now is to run the generator yourself locally using e.g. `node` or bingosync's [`gencard`](https://github.com/kbuzsaki/bingosync/blob/main/bingosync-app/bingosync/management/commands/gencard.py) django command, and then pass the json list of 25 goals in to the "Fixed Board" variant of the "Custom (Advanced)" game type.

For simple and SRL style goal lists Bingosync has the built-in ability to test goal lists by pasting the goal list in as json, but I haven't implemented that yet for synerGen.
