### ISSUE TITLE
New Generator Request

### ISSUE THREAD

**Issue by Eldendawgs** [kbuzsaki/bingosync#367]
[EldendawgsBeginner.txt](https://github.com/user-attachments/files/17581871/EldendawgsBeginner.txt)

The attached txt file is for the simple list.
Name for Room Creation dropdown: Eldendawgs
Name for Room List: Eldendawgs

Thank you so much for your time and effort!!

**Comment by Eldendawgs** [comment]
Yes! Sorry that was my intent for it. I see I didn't clarify that at all.
Sorry!

**Comment by kbuzsaki** [comment]
This is up on the site now :)
