### ISSUE TITLE
Updated list of goals request: Lil Gator Game

### ISSUE THREAD

**Issue by DanFloydPlus** [kbuzsaki/bingosync#368]
After some more rigorous testing with some of the game's best speedrunners, I've refined the existing Lil Gator Game randomized goal list for better overall pacing. Thanks!

GOAL LIST: https://pastebin.com/KJmVNVFQ#A6xTMhtP

**Comment by kbuzsaki** [comment]
This is up on the site now :)

**Comment by DanFloydPlus** [comment]
Heck yeah, thank you!
