### ISSUE TITLE
Splatoon 2 Octo Expansion Bingo

### ISSUE THREAD

**Issue by twitchchibi** [kbuzsaki/bingosync#48]
I would like SPlatoon 2 Octo Expansion added to Bingosync

var bingoList = [];
bingoList[1] = [
    {name: "A05 w/ splat bombs", types: ["A", "early"]},
    {name: "Break All Tutorial Area Boxes", types: ["early"]}
];

bingoList[2] = [
    {name: "Splat 5 Octosnipers", types: ["enemy"]},
    {name: "Complete 2 connector (square) stations", types: ["lines"]},
    {name: "Unlock 2 lines", types: ["lines"]},
    {name: "Get a loan from Marina and pay it back", types: ["credits"]}
];

bingoList[3] = [
    {name: "All levels on yellow line", types: ["A"]},
    {name: "Beat 1 boss", types: ["boss"]},
    {name: "1 Thang", types: ["thang"]},
    {name: "Splat 5 Octolings", types: ["octo"]},
    {name: "Beat 2 levels using Baller", types: ["baller"]}
];

bingoList[4] = [
    {name: "Beat all levels on 2 lines", types: ["lines"]},
    {name: "C02 w/o goal Balloon Fish", types: ["ink"]},
    {name: "Splat 5 OctoCommanders", types: ["enemy"]},
    {name: "Beat a station using all 3 supplied weapons", types: ["misc"]},
    {name: "Complete 4 connector (square) stations", types: ["lines"]}
];

bingoList[5] = [
    {name: "Beat all levels on blue line [H]", types: ["H", "lines"]},
    {name: "5000 credits", types: ["credits"]},
    {name: "I05/B08 w/ the Bamboozler", types: ["I", "B"]},
    {name: "Beat 2 levels using inkjet", types: ["inkjet"]},
    {name: "J04 w/ the inkbrush", types: ["J", "inkbrush"]},
    {name: "Splat 5 OctoBombers", types: ["enemy"]}
];

bingoList[6] = [
    {name: "Splat 10 Octolings", types: ["octo"]},
    {name: "Complete 6 connector (square) stations", types: ["lines"]},
    {name: "Beat 2 “Balloon Pop” levels", types: ["balloon"]},
    {name: "Collect 5 armor upgrades", types: ["armor"]},
    {name: "Beat 3 levels using a roller", types: [""]},
    {name: "I02 without grabbing ink refills", types: ["I", "ink"]}
];

bingoList[7] = [
    {name: "J03/D08 with the Splat Charger", types: ["J", "D"]},
    {name: "F02 w/ burst bombs only", types: ["F"]},
    {name: "J02 w/ Rapid blaster pro", types: ["J"]},
    {name: "Beat 3 levels using a brush", types: ["brush"]},
    {name: "Splat 10 Octosnipers", types: ["enemy"]},
    {name: "Beat both rainmaker levels", types: ["rainmaker"]}
];

bingoList[8] = [
    {name: "Beat 3 levels using dualies", types: ["dual"]},
    {name: "Beat 3 levels using a slosher", types: ["slosher"]},
    {name: "Collect 2 thangs", types: ["thang"]},
    {name: "Beat all levels on purple line", types: ["G", "lines"]},
    {name: "Beat 3 levels using a brella", types: ["brella"]},
    {name: "Collect 15 power egg containers", types: ["credits"]},
    {name: "J02 w/ splat charger ", types: ["J", "charger"]}
];

bingoList[9] = [
    {name: "Beat all levels on gray line", types: ["D", "lines"]},
    {name: "Beat all levels on lime line", types: ["I", "lines"]},
    {name: "Complete E10 “Cratebuster Station” with splat charger", types: ["E", "charger"]},
    {name: "Beat 3 levels using a splatling", types: ["splatling"]},
    {name: "Beat 2 stations using all 3 supplied weapons", types: ["misc"]},
    {name: "Fly through every ring in G10/E07", types: ["G", "E", "inkjet"]}
];

bingoList[10] = [
    {name: "Beat all levels on black line", types: ["F", "lines"]},
    {name: "Unlock 6 lines", types: ["lines"]},
    {name: "Beat 3 levels using a charger", types: ["charger"]},
    {name: "Beat 2 8 Ball levels", types: ["8ball"]},
    {name: "Complete 10 connector (square) stations", types: ["lines"]},
    {name: "Splat 10 Octocommanders", types: ["enemy"]}
];

bingoList[11] = [
    {name: "Beat all levels on pink line", types: ["J", "lines"]},
    {name: "Beat 5 levels using a roller", types: ["roller"]},
    {name: "Beat 4 8-Ball levels", types: ["8ball"]},
    {name: "Beat 3 levels using inkjet", types: ["inkjet"]},
    {name: "Collect 20 power egg containers", types: ["credits"]},
    {name: "Beat 5 levels using a brush", types: ["brush"]}
];

bingoList[12] = [
    {name: "Beat 3 levels using Baller", types: ["baller"]},
    {name: "Beat all levels on green line", types: ["C", "lines"]},
    {name: "Beat both data point stages", types: ["E", "F"]},
    {name: "Beat both tower control levels", types: ["H", "B"]},
    {name: "Get at least 10000 credits", types: ["credits"]},
    {name: "Beat 3 “Balloon Pop” levels", types: ["balloon"]}
];

bingoList[13] = [
    {name: "Beat all levels on teal line", types: ["B", "lines"]},
    {name: "Beat 5 levels using dualies", types: ["dual"]},
    {name: "Complete 13 connector (square) stations", types: ["lines"]},
    {name: "G02 w/ the Dynamo Roller", types: ["G", "roller"]},
    {name: "E09 w/ only Burst Bombs", types: ["E"]},
    {name: "Splat 15 Octosnipers", types: ["enemy"]}
];

bingoList[14] = [
    {name: "Unlock 8 lines", types: ["lines"]},
    {name: "Beat 2 boss fights", types: ["boss"]},
    {name: "Beat both match the shape stages", types: ["F", "J"]},
    {name: "Beat 5 levels using a slosher", types: ["slosher"]},
    {name: "I01/G01 with the Octobrush", types: ["boss", "brush"]},
    {name: "Beat 3 stages using all 3 supplied weapons", types: ["misc"]}
];

bingoList[15] = [
    {name: "Beat all levels on magenta line", types: ["E", "lines"]},
    {name: "Beat 7 levels using a roller", types: ["roller"]},
    {name: "Beat both “defend the orb” levels", types: ["J", "D", "I", "E"]},
    {name: "Beat 5 levels using a brella", types: ["brella"]},
    {name: "Collect 30 power egg containers", types: ["credits"]},
    {name: "Splat 15 Octolings", types: ["octo"]}
];

bingoList[16] = [
    {name: "Beat 5 levels using a splatling", types: ["splatling"]},
    {name: "Beat 6 8-Ball levels", types: ["8ball"]},
    {name: "Beat all 4 limited ink stages", types: ["ink"]},
    {name: "Complete 16 connector (square) stations", types: ["lines"]},
    {name: "Splat 10 Octobombers", types: ["enemy"]}
];

bingoList[17] = [
    {name: "Beat all levels on 4 lines", types: ["lines"]},
    {name: "Beat 5 levels using inkjet", types: ["inkjet"]},
    {name: "Beat 4 “Balloon Pop” levels", types: ["balloon"]},
    {name: "Collect 3 thangs", types: ["thang"]},
    {name: "Unlock all 10 lines", types: ["lines"]}
];

bingoList[18] = [
    {name: "Beat 3 boss fights", types: ["boss"]},
    {name: "Beat 5 levels using a charger", types: ["charger"]},
    {name: "Beat 7 levels using a brella", types: ["brella"]},
    {name: "Get at least 15000 credits", types: ["credits"]},
    {name: "Splat 15 Octocommanders", types: ["enemy"]},
    {name: "Collect 10 armor upgrades", types: ["armor"]}
];

bingoList[19] = [
    {name: "Beat 7 levels using a slosher", types: ["slosher"]},
    {name: "Beat 7 levels using a brush", types: ["brush"]},
    {name: "Beat 8 8-Ball levels", types: ["8ball"]},
    {name: "Splat 20 Octosnipers", types: ["enemy"]},
    {name: "Collect 40 power egg containers", types: ["credits"]}
];

bingoList[20] = [
    {name: "Beat all levels on 6 lines", types: ["lines"]},
    {name: "Beat 7 levels using a splatling", types: ["splatling"]},
    {name: "Beat 10 levels using a roller", types: ["roller"]},
    {name: "Complete all 20 connector (square) stations", types: ["lines"]},
    {name: "Get at least 20000 credits", types: ["credits"]},
];

bingoList[21] = [
    {name: "Beat all 4 boss fights", types: ["boss"]},
    {name: "Beat 7 levels using a charger", types: ["charger"]},
    {name: "Splat 20 Octocommanders", types: ["enemy"]}
];

bingoList[22] = [
    {name: "Beat 12 levels using a roller", types: ["roller"]},
    {name: "Collect all 4 thangs", types: ["thang"]}
];

bingoList[23] = [
    {name: "Beat 9 levels using a brush", types: ["brush"]},
    {name: "Get at least 25000 credits", types: ["credits"]},
    {name: "Splat 25 Octosnipers", types: ["enemy"]},
    {name: "Collect 50 power egg containers", types: ["credits"]}
];

bingoList[24] = [
    {name: "Beat all 10 8 Ball levels", types: ["8ball"]},
    {name: "Splat 15 Octobombers", types: ["enemy"]},
    {name: "Collect 15 armor upgrades", types: ["armor"]}
];

bingoList[25] = [
    {name: "Beat all levels on 8 lines", types: ["long", "lines"]},
    {name: "Get at least 30000 credits", types: ["long", "credits"]}
];
$(function() { srl.bingo(bingoList, 5); });

**Comment by twitchchibi** [comment]
Abbreviaton: Splatoon 2: OE

**Comment by kbuzsaki** [comment]
up on the site now :)
