### ISSUE TITLE
Cardfight!! Vanguard Bingo

### ISSUE THREAD

**Issue by RomainWang** [kbuzsaki/bingosync#51]
Hello, I want a bingo for the card game Cardfight!! Vanguard

Game: Cardfight!! Vanguard
Abbreviation: CFVG
Goals: https://pastebin.com/UGTDuctL

Thanks c:

**Comment by kbuzsaki** [comment]
Added in 5ecbb5b8bb7da8dd28b45e541fd92be1e55c2d24 and deployed to the site :)
