### ISSUE TITLE
Allow for more than 25 items in JSON list; select them randomly

### ISSUE THREAD

**Issue by qwoodmansee** [kbuzsaki/bingosync#60]
I am interested in this feature, and if it will be approved I am willing to implement it,

I was thinking I could implement a new function into forms.py, where in clean.py, instead of denying any board where len() != 25, I will instead check if len() > 25, call a function which randomly reduces the list down to 25, then continues on with that board. 

I have a goal list of more than 100 goals, and am currently having to pick them randomly before hand using this tool.

**Comment by kbuzsaki** [comment]
Thanks for the interest in this-- the reason I haven't implemented something like this before is concern about how to make the user interface easy and intuitive. What are your thoughts here?

In particular, I'm concerned about the case where someone might accidentally have a goal list with ~26 elements, thinking that they have only 25 elements, which then causes the board to be silently scrambled.

**Comment by FelixNemis** [comment]
Scrambling might be nice for only 25 goals too, maybe it could be a seperate checkbox and if you ha more than 25 and didn't scramble it would just show the first 25 I guess

**Comment by kbuzsaki** [comment]
This was implemented in 4d36f0ab712ecd30202f0e253a9bafd1f5a4a206 as the "Randomized" variant of the "Custom" `game_type`, rather than through a separate checkbox.
