### ISSUE TITLE
Feature request: Add a bingo counter

### ISSUE THREAD

**Issue by PikalaxALT** [kbuzsaki/bingosync#67]
With the allowance for up to 10 simultaneous racers, it can be hard to keep track of what goals each person has, or even how many bingos you have (in a triple or cinco bingo setting).  This is challenging even with only two racers.  What would resolve this is a counter for how many rows, columns, or diagonals have been completed by each racer in non-lockout mode.

**Comment by kbuzsaki** [comment]
Implemented in 4836f997f9cecc912b0a4c6f8de3abbcbebedbaa :)
