### ISSUE TITLE
New Bingo - Dragon Warrior Monsters

### ISSUE THREAD

**Issue by TheFoolsGambit** [kbuzsaki/bingosync#71]
Let me know if I missed anything, or did the syntax wrong.

1: Generator:

bingoGenerator = require("./generators/generator_bases/srl_generator_v5.js");

var bingoList = [];

bingoList[1] = [
  { name: "DrakSlime or DragonKid", types: ["breed"] },
  { name: "Windbeast or MadCandle", types: ["breed"] },
  { name: "MadRaven or RotRaven", types: ["breed"] },
  { name: "Gulpple or DarkEye", types: ["breed"] },
];
bingoList[2] = [
  { name: "SpotSlime or Tonguella", types: ["breed"] },
  { name: "MistyWing or CoilBird", types: ["breed"] },
  { name: "Toadstool or Mummy", types: ["breed"] },
  { name: "GiantWorm or EyeBall", types: ["breed"] },
];
bingoList[3] = [
  { name: "WingSlime or Picky", types: ["breed"] },
  { name: "Tortagon or Almiraj", types: ["breed"] },
  { name: "AmberWeed or Facer", types: ["breed"] },
  { name: "Lipsy or DarkCrab", types: ["breed"] },
];
bingoList[4] = [
  { name: "TreeSlime or MadPlant", types: ["breed"] },
  { name: "Pteranod or Wyvern", types: ["breed"] },
  { name: "StagBug or SpikyBoy", types: ["breed"] },
  { name: "SkulRider or DeadNite", types: ["breed"] },
];
bingoList[5] = [
  { name: "Snaily or GiantSlug", types: ["breed"] },
  { name: "Gasgon or FireWeed", types: ["breed"] },
  { name: "Catfly or BullBird", types: ["breed"] },
  { name: "EvilBeast or MadMirror", types: ["breed"] },
];
bingoList[6] = [
  { name: "SlimeNite or Pixy", types: ["breed"] },
  { name: "FairyDrak or Catapila", types: ["breed"] },
  { name: "PillowRat or FloraMan", types: ["breed"] },
  { name: "Shadow or RogueNite", types: ["breed"] },
];
bingoList[7] = [
  { name: "Babble or Spooky", types: ["breed"] },
  { name: "LizardMan or MedusaEye", types: ["breed"] },
  { name: "Saccer or Gophecada", types: ["breed"] },
  { name: "FloraJay or WingTree", types: ["breed"] },
];
bingoList[8] = [
  { name: "BoxSlime or JewelBag", types: ["breed"] },
  { name: "Poisongon or MadSpirit", types: ["breed"] },
  { name: "Grizzly or Gremlin", types: ["breed"] },
  { name: "DuckKite or Butterfly", types: ["breed"] },
];
bingoList[9] = [
  { name: "Swordgon or EvilWand", types: ["breed"] },
  { name: "Skullroo or Putrepup", types: ["breed"] },
  { name: "MadPecker or Demonite", types: ["breed"] },
  { name: "Cactiball or WeedBug", types: ["breed"] },
];
bingoList[10] = [
  { name: "Unicorn", types: ["breed"] },
  { name: "Roboster", types: ["breed"] },
  { name: "Phoenix", types: ["breed"] },
  { name: "Lionex", types: ["breed"] },
];
bingoList[11] = [
  { name: "ManEater", types: ["breed"] },
  { name: "HornBeet", types: ["breed"] },
  { name: "ChopClown", types: ["breed"] },
  { name: "BoneSlave", types: ["breed"] },
];
bingoList[12] = [
  { name: "5 Different Slimes", types: ["breed"] },
  { name: "5 Different Dragons", types: ["breed"] },
  { name: "5 Different Beasts", types: ["breed"] },
  { name: "5 Different Birds", types: ["breed"] },
];
bingoList[13] = [
  { name: "5 Different Plants", types: ["breed"] },
  { name: "5 Different Bugs", types: ["breed"] },
  { name: "5 Different Devils", types: ["breed"] },
  { name: "5 Different Zombies", types: ["breed"] },
];
bingoList[14] = [
  { name: "C-Class", types: ["progress"] },
  { name: "B-Class", types: ["progress"] },
  { name: "A-Class", types: ["progress"] },
  { name: "S-Class", types: ["progress"] },
];
bingoList[15] = [
  { name: "G-Class", types: ["progress"] },
  { name: "F-Class", types: ["progress"] },
  { name: "E-Class", types: ["progress"] },
  { name: "D-Class", types: ["progress"] },
];
bingoList[16] = [
  { name: "Joy Gate (FunkyBird)", types: ["progress"] },
  { name: "Wisdom Gate (SkyDragon)", types: ["progress"] },
  { name: "5 Different Materials", types: ["breed"] },
  { name: "Colosseum Gate (Digster)", types: ["progress"] },
];
bingoList[17] = [
  { name: "Anger Gate (BattleWrex)", types: ["progress"] },
  { name: "Well Gate (Gigantes)", types: ["progress"] },
  { name: "Strength Gate (StoneMan)", types: ["progress"] },
  { name: "Monster Farm Gate (CopyCat)", types: ["progress"] },
];
bingoList[18] = [
  { name: "Memories Gate (MadCat)", types: ["progress"] },
  { name: "Bewilder Gate (FaceTree)", types: ["progress"] },
  { name: "Peace Gate (FangSlime)", types: ["progress"] },
  { name: "Bravery Gate (BigEye)", types: ["progress"] },
];
bingoList[19] = [
  { name: "Beginning Gate (Healer)", types: ["progress"] },
  { name: "Villager Gate (Dragon)", types: ["progress"] },
  { name: "Talisman Gate (Golem)", types: ["progress"] },
  { name: "Bazaar Gate (MadNite)", types: ["progress"] },
];
bingoList[20] = [
  { name: "'King' monster", types: ["breed"] },
  { name: "'Mad' monster", types: ["breed"] },
  { name: "'Nite' monster", types: ["breed"] },
  { name: "Double letters in name (ex: gOOpi, ducKKite)", types: ["breed"] },
];
bingoList[21] = [
  { name: "3 Level 30+ Monsters", types: ["train"] },
  { name: "No limbs (excluding Slib)", types: ["breed"] },
  { name: "One Eye", types: ["breed"] },
  { name: "BigRoost or GoHopper or CopyCat or Watabou", types: ["breed"] },
];
bingoList[22] = [
  { name: "+5 Monster", types: ["breed"] },
  { name: "Breed 10 Monsters", types: ["breed"] },
  { name: "Breed 4 times with other masters", types: ["breed"] },
  { name: "Breed Slib", types: ["breed"] },
];
bingoList[23] = [
  { name: "Any Book", types: ["item"] },
  { name: "BeastTail", types: ["item"] },
  { name: "13 Tiny Medals", types: ["item"] },
  { name: "Badmeat", types: ["item"] },
];
bingoList[24] = [
  { name: "Beat 3 Masters in wild", types: ["choice"] },
  { name: "Pick up no items in a gate", types: ["choice"] },
  { name: "Hatch an egg without checking gender", types: ["choice"] },
  { name: "Turn away all monsters in a gate", types: ["choice"] },
];
bingoList[25] = [
  { name: "'slash' skill", types: ["breed"] },
  { name: "Tatsu/Diago/Samsi/Bazoo-call", types: ["breed"] },
  { name: "'dance' skill", types: ["breed"] },
  { name: "Type counter skill (ex: BeastCut, SmashSlime", types: ["breed"] },
];

2: Name: Dragon Warrior Monsters
3: DWM

**Comment by kbuzsaki** [comment]
Up on the site now.

The generator syntax was correct, but having the same type so many times will usually make the generator start ignoring types out of necessity-- it can't build a board while respecting them. So I would recommend using types on fewer goals or making types that are more specific.
