### ISSUE TITLE
Add new bingo card (Myst)

### ISSUE THREAD

**Issue by admiralflapjack** [kbuzsaki/bingosync#81]
[mystbingo.txt](https://github.com/kbuzsaki/bingosync/files/3665840/mystbingo.txt)
Should be in proper SRL format.

**Comment by admiralflapjack** [comment]
Oh, the name of the card and the shortname can both be Myst.

**Comment by admiralflapjack** [comment]
[mystbingo.txt](https://github.com/kbuzsaki/bingosync/files/3672842/mystbingo.txt)
The card went through debugging, this should be a corrected version. Ignore the original file, it is deprecated.

**Comment by kbuzsaki** [comment]
Up on the site now with the second goal list :)
