### ISSUE TITLE
Update Yooka-Laylee Board

### ISSUE THREAD

**Issue by tipdaddy78** [kbuzsaki/bingosync#92]
Hi, we updated the balancing and changed up some of the goals for yooka-laylee's bingo board if you wouldn't mind getting it updated.

https://pastebin.com/SEQ9vxTJ

Thanks!

**Comment by kbuzsaki** [comment]
Alright, it's up on the site now :)

**Comment by tipdaddy78** [comment]
Thanks much!!!
